package bosca.kubernetes.controller.route

import bosca.routes.Route
import bosca.security.service.AuthenticationContext
import bosca.server.ContentType
import bosca.server.HttpStatusCode
import bosca.server.ServerCall
import bosca.server.StreamingResponse
import io.fabric8.kubernetes.api.model.GenericKubernetesResource
import io.fabric8.kubernetes.api.model.GenericKubernetesResourceList
import io.fabric8.kubernetes.client.KubernetesClient
import io.fabric8.kubernetes.client.dsl.MixedOperation
import io.fabric8.kubernetes.client.dsl.Resource
import io.fabric8.kubernetes.client.dsl.base.ResourceDefinitionContext
import io.mockk.coEvery
import io.mockk.every
import io.mockk.justRun
import io.mockk.mockk
import java.io.ByteArrayOutputStream
import java.nio.charset.StandardCharsets
import kotlin.coroutines.Continuation
import kotlin.coroutines.intrinsics.suspendCoroutineUninterceptedOrReturn

/**
 * Test-only helper that calls the protected
 * `Route.execute(ServerCall, AuthenticationContext)` via reflection.
 *
 * Routes are concrete `final` classes (Kotlin default) and the inner
 * `execute` is `protected`, so a test cannot subclass to expose the
 * method. Reflection keeps the production code free of test-only
 * visibility changes.
 *
 * The lookup walks up the class hierarchy because the override is on
 * the route subclass while the abstract declaration is on
 * [bosca.routes.Route]; the generated bytecode places the method on
 * the subclass with the parent's `protected` visibility.
 */
/**
 * Test-only helper for routes that touch fabric8's
 * `client.genericKubernetesResources(ctx)` API. Returns a per-kind
 * [GenericResourceStub] that callers wire up with the list responses
 * they want.
 *
 * Why this exists: a single test often stubs the same chain for
 * multiple [ResourceDefinitionContext] kinds (Cluster + Backup +
 * ScheduledBackup; Certificate + Issuer + ClusterIssuer). mockk's
 * default deep mocking returns the *same* intermediate mock for each
 * `genericKubernetesResources(...)` call regardless of argument, so
 * the last `every { ... .inAnyNamespace().list() } returns ...` setup
 * silently overrides earlier ones. The dispatcher captures the
 * context argument at call time and routes to a distinct stub per
 * `kind`, so each kind's list call is honored independently.
 */
fun KubernetesClient.stubGenericResources(): GenericResourceDispatcher {
    val dispatcher = GenericResourceDispatcher()
    every { genericKubernetesResources(any<ResourceDefinitionContext>()) } answers {
        val ctx = firstArg<ResourceDefinitionContext>()
        dispatcher.opsFor(ctx.kind)
    }
    return dispatcher
}

class GenericResourceDispatcher {
    private val stubs = mutableMapOf<String, GenericResourceStub>()

    /** Returns (creating on first use) the stub for `kind`. */
    fun forKind(kind: String): GenericResourceStub = stubs.getOrPut(kind) { GenericResourceStub() }

    /** Returns the underlying `MixedOperation` mock so the dispatcher can answer with it. */
    internal fun opsFor(kind: String) = forKind(kind).ops
}

class GenericResourceStub {
    val ops: MixedOperation<GenericKubernetesResource, GenericKubernetesResourceList, Resource<GenericKubernetesResource>> =
        mockk(relaxed = true)

    fun listInAnyNamespace(vararg items: GenericKubernetesResource): GenericResourceStub {
        every { ops.inAnyNamespace().list() } returns listOf(*items)
        return this
    }

    fun listInNamespace(namespace: String, vararg items: GenericKubernetesResource): GenericResourceStub {
        every { ops.inNamespace(namespace).list() } returns listOf(*items)
        return this
    }

    fun listClusterScoped(vararg items: GenericKubernetesResource): GenericResourceStub {
        every { ops.list() } returns listOf(*items)
        return this
    }

    fun throwsOnInAnyNamespace(t: Throwable): GenericResourceStub {
        every { ops.inAnyNamespace().list() } throws t
        return this
    }

    fun throwsOnInNamespace(namespace: String, t: Throwable): GenericResourceStub {
        every { ops.inNamespace(namespace).list() } throws t
        return this
    }

    fun throwsOnClusterList(t: Throwable): GenericResourceStub {
        every { ops.list() } throws t
        return this
    }

    private fun listOf(vararg items: GenericKubernetesResource): GenericKubernetesResourceList {
        val list = GenericKubernetesResourceList()
        list.items = items.toMutableList()
        return list
    }
}

/**
 * Test capture for routes that write through `call.response.respondStreaming`.
 *
 * Mocks `call.response.respondStreaming` so the streaming block runs
 * inline against a [StreamingResponse] mock that funnels every
 * `write(...)` into [bytes]. Call [text] / [lines] to inspect what
 * the route emitted.
 *
 * Use [register] before invoking the route; the streaming block is
 * invoked on the caller's coroutine so the test can drive watchers /
 * close channels and let the block return naturally.
 */
class StreamingCapture(call: ServerCall) {
    private val baos = ByteArrayOutputStream()
    val output: StreamingResponse = mockk(relaxed = true)
    val contentType: ContentType?
        get() = capturedContentType
    private var capturedContentType: ContentType? = null

    init {
        coEvery { output.write(any(), any(), any()) } answers {
            val bytes = firstArg<ByteArray>()
            val offset = secondArg<Int>()
            val length = thirdArg<Int>()
            baos.write(bytes, offset, length)
        }
        coEvery { output.write(any()) } answers {
            val bytes = firstArg<ByteArray>()
            baos.write(bytes)
        }
        coEvery { output.flush() } returns Unit
        wire(call)
    }

    private fun wire(call: ServerCall) {
        coEvery { call.response.respondStreaming(any(), any(), any()) } coAnswers {
            capturedContentType = firstArg<ContentType>()
            @Suppress("UNCHECKED_CAST")
            val block = thirdArg<suspend (StreamingResponse) -> Unit>()
            block(output)
        }
    }

    val text: String get() = baos.toString(StandardCharsets.UTF_8)
    val lines: List<String> get() = text.split("\n").filter { it.isNotBlank() }
}

fun ServerCall.captureStream(): StreamingCapture = StreamingCapture(this)

@Suppress("UNCHECKED_CAST")
suspend fun <T> Route<T>.runExecute(call: ServerCall, ctx: AuthenticationContext): T? {
    // Find the suspend variant — bytecode signature has a trailing Continuation parameter.
    val method = generateSequence<Class<*>>(this::class.java) { it.superclass }
        .flatMap { it.declaredMethods.asSequence() }
        .firstOrNull { m ->
            m.name == "execute" &&
                m.parameterTypes.size == 3 &&
                m.parameterTypes[0] == ServerCall::class.java &&
                m.parameterTypes[1] == AuthenticationContext::class.java &&
                m.parameterTypes[2] == Continuation::class.java
        }
        ?: error("could not find execute(ServerCall, AuthenticationContext) on ${this::class.java}")
    method.isAccessible = true
    return suspendCoroutineUninterceptedOrReturn<Any?> { cont ->
        try {
            method.invoke(this, call, ctx, cont)
        } catch (e: java.lang.reflect.InvocationTargetException) {
            // Surface the original exception so tests can assertFailsWith on the real type
            // instead of the reflection wrapper.
            throw e.targetException
        }
    } as T?
}
