package bosca.recommendations.model

import bosca.db.annotation.ColumnName
import bosca.serialization.OffsetDateTime
import bosca.serialization.UUID
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * A precomputed behavioral co-engagement edge: audiences who engaged with [sourceMetadataId] also
 * engaged with [coEngagedMetadataId] ("people who engaged with this also engaged with…"). Generated by a
 * [RecommendationStrategyType.CO_ENGAGEMENT] strategy from a co-occurrence analytics query and served,
 * item-anchored, at the source item's context. This is a *behavioral* signal — distinct from content
 * *similarity* — and, unlike [Recommendation], is keyed on a source item rather than a profile.
 */
@Serializable
data class CoEngagement(
    @ColumnName("source_metadata_id")
    @Contextual
    val sourceMetadataId: UUID,
    @ColumnName("co_engaged_metadata_id")
    @Contextual
    val coEngagedMetadataId: UUID,
    @ColumnName("strategy_id")
    @Contextual
    val strategyId: UUID,
    val score: Double = 0.0,
    val reason: String? = null,
    @Contextual
    val created: OffsetDateTime = OffsetDateTime.now(),
)
