package bosca.recommendations.model

import bosca.db.annotation.ColumnName
import bosca.serialization.OffsetDateTime
import bosca.serialization.UUID
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable

/**
 * A precomputed "people like you" co-engagement edge: members of [cohortKey] who engaged with
 * [sourceMetadataId] also engaged with [coEngagedMetadataId]. Like [CoEngagement] but conditioned on a
 * cohort membership — a keyed value derived from a viewer's useAsCohort Personalization Signals (see the
 * `profile_cohort` view). Generated by a [RecommendationStrategyType.COHORT_CO_ENGAGEMENT] strategy from a
 * per-cohort co-occurrence analytics query and served, item-anchored, to viewers who belong to the cohort.
 */
@Serializable
data class CohortCoEngagement(
    @ColumnName("source_metadata_id")
    @Contextual
    val sourceMetadataId: UUID,
    @ColumnName("cohort_key")
    val cohortKey: String,
    @ColumnName("co_engaged_metadata_id")
    @Contextual
    val coEngagedMetadataId: UUID,
    @ColumnName("strategy_id")
    @Contextual
    val strategyId: UUID,
    val score: Double = 0.0,
    val reason: String? = null,
    @Contextual
    val created: OffsetDateTime = OffsetDateTime.now(),
)
