package bosca.server

import bosca.di.ProviderRegistrar
import bosca.di.ScriptingEngineProviderRegistrar

/**
 * Resolves the registrar that wires the `local-engine` and `local-execution-service`
 * providers (KtsEngine + LocalScriptExecutionServiceImpl).
 *
 * This is the `scriptingEnabled` source-set variant. It is selected by `build.gradle.kts`
 * when `-Pbosca.scripting.engine=true` (the default), so `bosca.di.ScriptingEngineProviderRegistrar`
 * — generated by KSP in the scripting-engine module — is on the classpath.
 *
 * The matching `scriptingDisabled` variant returns `null` so the build still compiles when
 * the scripting-engine module is excluded.
 */
object ScriptingEngineRegistrarProvider {
    fun get(): ProviderRegistrar? = ScriptingEngineProviderRegistrar()
}
