Args = --no-fallback \
       --enable-url-protocols=http,https \
       --initialize-at-build-time=ch.qos.logback,org.slf4j,org.xml.sax \
       --initialize-at-run-time=io.netty.util.internal,io.netty.handler.ssl,io.netty.handler.codec.compression,io.netty.channel.epoll,io.netty.channel.unix,io.netty.channel.kqueue \
       -H:+ReportExceptionStackTraces \
       -H:+UnlockExperimentalVMOptions \
       -H:+SharedArenaSupport
