mutation SetPipelineSecret($repositoryId: UUID!, $name: String!, $value: String!) {
    git {
        setPipelineSecret(repositoryId: $repositoryId, name: $name, value: $value) {
            name
            created
            updated
        }
    }
}

mutation DeletePipelineSecret($repositoryId: UUID!, $name: String!) {
    git {
        deletePipelineSecret(repositoryId: $repositoryId, name: $name)
    }
}

query ListPipelineSecrets($repositoryId: UUID!) {
    git {
        pipelineSecrets(repositoryId: $repositoryId) {
            name
            created
            updated
        }
    }
}
