<script setup lang="ts">
definePageMeta({ layout: false })

useSeoMeta({
  title: 'AI Tools — Scripture your agents can quote',
  description: 'Bosca gives AI agents four tools to work with scripture — discover translations, list books, resolve references, and fetch verse text — and the words always come from the installed Bible translation, never invented by the language model.'
})

useDiscoverSeo([
  { name: 'Bosca', path: '/' },
  { name: 'Bible', path: '/discover/bible' },
  { name: 'AI Tools', path: '/discover/bible/ai' }
], '/og-bible.png')

const TOOLS = [
  { icon: 'list', name: 'List translations', body: 'Discover which Bibles are installed and available to read.' },
  { icon: 'book-open', name: 'List books', body: 'Enumerate the books of a translation, with their codes and names.' },
  { icon: 'quote', name: 'Resolve a reference', body: 'Turn a phrase like "John 3:16" into a canonical reference — before fetching a word.' },
  { icon: 'book', name: 'Fetch verses', body: 'Pull the actual scripture text for a reference, straight from the translation.' }
]
</script>

<template>
  <DiscoverShell section-id="bible">
    <section class="page-hero">
      <p class="kicker load-1">
        AI Tools
      </p>
      <h1 class="load-2">
        Scripture your <em>agents can quote</em>
      </h1>
      <p class="section-sub load-3">
        Give an AI agent scripture without the risk of a made-up verse. A small
        set of tools lets it discover translations, list books, resolve
        references, and fetch text — and the words always come from the
        installed Bible, never from the model.
      </p>
    </section>

    <!-- ── The tools ───────────────────────────── -->
    <section class="section">
      <div class="section-head reveal">
        <p class="kicker">
          The tools
        </p>
        <h2>Four ways to <em>reach the text</em></h2>
        <p class="section-sub">
          Each tool does one thing well, so an agent can plan its way from a
          question to the exact scripture it needs — one step at a time.
        </p>
      </div>
      <div class="tool-grid reveal">
        <article
          v-for="t in TOOLS"
          :key="t.name"
          class="tool-card"
        >
          <span class="tool-icon">
            <Icon
              :name="t.icon"
              :size="16"
            />
          </span>
          <h3>{{ t.name }}</h3>
          <p>{{ t.body }}</p>
        </article>
      </div>
    </section>

    <!-- ── Never invented ──────────────────────── -->
    <section class="section">
      <div class="split reveal">
        <div class="split-copy">
          <p class="kicker">
            Never invented
          </p>
          <h2>The model plans; <em>it doesn't quote</em></h2>
          <p class="section-sub">
            A language model is good at reasoning about a passage and terrible at
            reciting one exactly. So it never does. When an agent needs a verse,
            it calls a tool that reads the real text from the installed
            translation — the model decides what to look up, not what the verse
            says.
          </p>
          <ul class="point-list">
            <li>The verse text is read from the Bible, not generated by the model.</li>
            <li>The agent chooses references and books; the platform supplies the words.</li>
            <li>What it quotes is exactly what you imported — every time.</li>
          </ul>
        </div>
        <div class="agent-window">
          <div class="code-chrome">
            <span class="dot" /><span class="dot" /><span class="dot" />
            <span class="code-title">agent</span>
          </div>
          <div class="agent-body">
            <div class="agent-step think">
              <span class="agent-tag">plan</span>
              <span class="agent-text">the reader asked for John 3:16</span>
            </div>
            <div class="agent-step call">
              <span class="agent-tag">tool</span>
              <span class="agent-text"><code>bible_get_verses("John 3:16")</code></span>
            </div>
            <div class="agent-step result">
              <p>For God so loved the world, that he gave his one and only Son…</p>
              <span class="agent-src">
                <Icon
                  name="shield-check"
                  :size="11"
                />
                read from WEB · not generated
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <DiscoverBibleExplore />
  </DiscoverShell>
</template>

<style scoped>
/* ── Tool cards ──────────────────────────────── */

.tool-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 12px;
}

.tool-card {
  padding: 22px 20px;
  border: 1px solid var(--line);
  border-radius: var(--r-md);
  background: color-mix(in srgb, var(--bg-1) 55%, transparent);
  transition: border-color 0.2s ease, transform 0.2s ease;
}

.tool-card:hover {
  border-color: color-mix(in srgb, var(--accent) 45%, transparent);
  transform: translateY(-2px);
}

.tool-icon {
  width: 32px;
  height: 32px;
  border-radius: var(--r-xs);
  display: flex;
  align-items: center;
  justify-content: center;
  background: color-mix(in srgb, var(--accent) 18%, transparent);
  color: var(--accent);
  margin-bottom: 13px;
}

.tool-card h3 {
  font-size: 14.5px;
  font-weight: 650;
  margin: 0 0 7px;
}

.tool-card p {
  font-size: 12.5px;
  line-height: 1.6;
  color: var(--fg-2);
  margin: 0;
}

/* ── Agent window ────────────────────────────── */

.agent-window {
  border: 1px solid var(--line-2);
  border-radius: var(--r-md);
  background: var(--bg-0);
  overflow: hidden;
  box-shadow: 0 24px 60px rgba(0, 0, 0, 0.4);
}

.agent-body {
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.agent-step {
  padding: 13px 15px;
  border: 1px solid var(--line);
  border-radius: var(--r-sm);
  background: color-mix(in srgb, var(--bg-1) 55%, transparent);
}

.agent-step.think,
.agent-step.call {
  display: flex;
  align-items: center;
  gap: 11px;
}

.agent-tag {
  font-family: var(--font-mono);
  font-size: 9.5px;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--fg-3);
  border: 1px solid var(--line-2);
  border-radius: 999px;
  padding: 2px 8px;
  flex-shrink: 0;
}

.agent-text {
  font-size: 13px;
  color: var(--fg-1);
}

.agent-text code {
  font-family: var(--font-mono);
  font-size: 12px;
  color: var(--accent);
}

.agent-step.result {
  border-color: color-mix(in srgb, var(--accent) 35%, transparent);
  background: color-mix(in srgb, var(--accent) 8%, transparent);
}

.agent-step.result p {
  font-family: var(--font-display);
  font-style: italic;
  font-size: 16px;
  color: var(--fg-0);
  margin: 0 0 10px;
}

.agent-src {
  display: flex;
  align-items: center;
  gap: 6px;
  font-family: var(--font-mono);
  font-size: 10.5px;
  color: var(--accent);
}

/* ── Responsive ──────────────────────────────── */

@media (max-width: 860px) {
  .tool-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 500px) {
  .tool-grid {
    grid-template-columns: 1fr;
  }
}
</style>
