package bosca.di

/**
 * Registers one or more [ObjectProvider] instances into the [ProviderRegistry].
 *
 * Implementations are typically generated by KSP and called at startup to
 * populate the DI container with all known providers.
 */
interface ProviderRegistrar {

    /** Registers this registrar's providers into the [ProviderRegistry]. */
    fun register()
}