package bosca.bml.codegen

import bosca.bml.parser.AttrText
import bosca.bml.parser.Attribute
import bosca.bml.parser.Document
import bosca.bml.parser.ElementNode
import bosca.bml.parser.EventAttribute
import bosca.bml.parser.ForNode
import bosca.bml.parser.IfNode
import bosca.bml.parser.Node
import bosca.bml.parser.RawKind
import bosca.bml.parser.RawTextNode
import bosca.bml.parser.StaticAttribute
import bosca.bml.tags.BuiltinTags

/**
 * Generates the client-side TypeScript module for a BML source file. Page scripts remain ordinary
 * module code. Island scripts and opt-in `<script client scoped>` component scripts become isolated
 * runtime setups with typed `ctx.refs`, programmatic server actions, and automatic lifecycle cleanup.
 */
class BmlClientCodeGenerator {

    fun generate(document: Document, hasTransitiveClientRuntime: Boolean = false): String? {
        val pageScripts = mutableListOf<String>()
        val islands = mutableListOf<Island>()
        val components = mutableListOf<ClientComponent>()
        collect(document.nodes, null, null, pageScripts, islands, components)
        val hasDeferred = hasDeferredIsland(document.nodes)
        val hasEvents = hasEventAttribute(document.nodes)
        val hasLocalClientRuntime = pageScripts.isNotEmpty() || islands.isNotEmpty() ||
            components.isNotEmpty() || hasEvents || hasDeferred
        val bootstrapSharedIdentity = hasSharedCachePage(document.nodes) &&
            (hasLocalClientRuntime || hasTransitiveClientRuntime)
        val enableRuntime = hasDeferred || bootstrapSharedIdentity
        // Unscoped component scripts are legacy module-level scripts just like page scripts. Their
        // inline `on*` attributes still resolve names through `window`, so include component markup
        // when discovering compatibility exports. Fully scoped component-only modules have no
        // [pageScripts] and therefore publish nothing.
        val handlers = clientHandlerNames(document.nodes)
        if (pageScripts.isEmpty() && islands.isEmpty() && components.isEmpty()) {
            if (!hasEvents && !enableRuntime) return null
            return buildString {
                appendLine("// Generated by the BML compiler plugin for BML client runtime startup — do not edit.")
                appendLine(
                    if (enableRuntime) """import { enableDeferred, mountAll } from "@bosca/bml""""
                    else """import { mountAll } from "@bosca/bml"""",
                )
                appendLine()
                if (enableRuntime) appendLine("enableDeferred()")
                appendLine("mountAll()")
            }
        }

        // Imports are module declarations and cannot remain inside the setup callbacks generated
        // for island/component scripts. Hoist them once, preserving each script's executable body.
        val imports = linkedSetOf<String>()
        fun hoist(content: String): String = CLIENT_IMPORT.replace(content) { match ->
            imports += match.value.trim()
            ""
        }
        val islandBodies = islands.map { it.copy(content = hoist(it.content)) }
        val componentBodies = components.map { it.copy(content = hoist(it.content)) }
        val moduleBodies = pageScripts.map(::hoist)

        return buildString {
            appendLine("// Generated by the BML compiler plugin from <script client> — do not edit.")
            val deferredImport = if (enableRuntime) ", enableDeferred" else ""
            appendLine(
                """import { defineComponent, defineIsland$deferredImport, mountAll, renderFragment } from "@bosca/bml"""",
            )
            imports.forEach(::appendLine)
            appendLine()
            if (enableRuntime) appendLine("enableDeferred()")
            islandBodies.forEach { island ->
                appendLine("defineIsland<${refsType(island.refs)}>(${jsString(island.name)}, (ctx) => {")
                dedent(rewriteProgrammaticActions(island.content)).forEach {
                    appendLine(if (it.isEmpty()) "" else "  $it")
                }
                appendLine("})")
                appendLine()
            }
            componentBodies.forEach { component ->
                appendLine("defineComponent<${refsType(component.refs)}>(${jsString(component.tag)}, (ctx) => {")
                dedent(rewriteProgrammaticActions(component.content)).forEach {
                    appendLine(if (it.isEmpty()) "" else "  $it")
                }
                appendLine("})")
                appendLine()
            }
            moduleBodies.forEach { script ->
                dedent(script).forEach(::appendLine)
                appendLine()
            }
            if (handlers.isNotEmpty() && pageScripts.isNotEmpty()) {
                // Legacy page/component inline handlers stay reachable. Scoped component code uses
                // ctx.on(ctx.refs.foo, ...) and component-only scoped modules publish no globals.
                appendLine("Object.assign(window, { ${handlers.joinToString(", ")} })")
            }
            appendLine("mountAll()")
        }
    }

    private data class Ref(val name: String, val domType: String)
    private data class Scope(val name: String, val element: ElementNode)
    private data class Island(val name: String, val content: String, val refs: List<Ref>)
    private data class ClientComponent(val tag: String, val content: String, val refs: List<Ref>)

    private fun collect(
        nodes: List<Node>,
        currentIsland: Scope?,
        currentComponent: Scope?,
        pageScripts: MutableList<String>,
        islands: MutableList<Island>,
        components: MutableList<ClientComponent>,
    ) {
        for (node in nodes) when (node) {
            is RawTextNode -> if (node.kind == RawKind.ClientScript) {
                when {
                    currentIsland != null -> islands += Island(
                        clientIslandName(currentIsland.name, currentComponent?.name),
                        node.content,
                        refs(currentIsland.element),
                    )
                    currentComponent != null && isScoped(node) -> components += ClientComponent(
                        currentComponent.name,
                        node.content,
                        refs(currentComponent.element),
                    )
                    else -> pageScripts += node.content
                }
            }
            is ElementNode -> {
                if (currentIsland?.element?.let(::isDeferredIsland) == true && isFallback(node)) continue
                val component = if (node.namespace == null && node.name == "component") {
                    Scope(staticString(node.attributes, "tag") ?: "component", node)
                } else currentComponent
                val island = if (node.namespace == null && node.name == "island") {
                    Scope(staticString(node.attributes, "name") ?: "island", node)
                } else currentIsland
                collect(node.children, island, component, pageScripts, islands, components)
            }
            is ForNode -> collect(node.children, currentIsland, currentComponent, pageScripts, islands, components)
            is IfNode -> {
                node.branches.forEach {
                    collect(it.children, currentIsland, currentComponent, pageScripts, islands, components)
                }
                node.elseChildren?.let {
                    collect(it, currentIsland, currentComponent, pageScripts, islands, components)
                }
            }
            else -> Unit
        }
    }

    private fun isScoped(script: RawTextNode): Boolean =
        script.attributes.any { it is StaticAttribute && it.name == "scoped" }

    private fun hasDeferredIsland(nodes: List<Node>): Boolean = nodes.any { node ->
        when (node) {
            is ElementNode -> {
                val deferred = node.namespace == null && node.name == "island" &&
                    staticString(node.attributes, "render") == "deferred"
                deferred || hasDeferredIsland(node.children)
            }
            is ForNode -> hasDeferredIsland(node.children)
            is IfNode ->
                node.branches.any { hasDeferredIsland(it.children) } ||
                    (node.elseChildren?.let(::hasDeferredIsland) ?: false)
            else -> false
        }
    }

    private fun hasSharedCachePage(nodes: List<Node>): Boolean = nodes.any { node ->
        node is ElementNode && node.namespace == null && node.name in setOf("page", "route") &&
            staticString(node.attributes, "cache") == "shared"
    }

    private fun isDeferredIsland(node: ElementNode): Boolean =
        node.namespace == null && node.name == "island" && staticString(node.attributes, "render") == "deferred"

    private fun isFallback(node: ElementNode): Boolean = node.namespace == null && node.name == "fallback"

    private fun clientIslandName(name: String, componentTag: String?): String =
        componentTag?.let { "component:$it:$name" } ?: name

    /** Named refs in one client scope, excluding nested component/island scopes. */
    private fun refs(scope: ElementNode): List<Ref> {
        val found = linkedMapOf<String, Ref>()
        fun walk(nodes: List<Node>) {
            for (node in nodes) when (node) {
                is ElementNode -> {
                    if (isDeferredIsland(scope) && isFallback(node)) continue
                    if (node !== scope && node.namespace == null && node.name in setOf("component", "island")) continue
                    staticString(node.attributes, "ref")?.takeIf { it.isNotBlank() }?.let { name ->
                        found.putIfAbsent(name, Ref(name, domType(node)))
                    }
                    walk(node.children)
                }
                is ForNode -> walk(node.children)
                is IfNode -> {
                    node.branches.forEach { walk(it.children) }
                    node.elseChildren?.let(::walk)
                }
                else -> Unit
            }
        }
        walk(scope.children)
        return found.values.toList()
    }

    private fun domType(element: ElementNode): String = when {
        element.namespace == "svg" || element.name in BuiltinTags.svg -> "SVGElement"
        else -> DOM_TYPES[element.name] ?: "HTMLElement"
    }

    private fun refsType(refs: List<Ref>): String = if (refs.isEmpty()) {
        "Record<string, never>"
    } else {
        refs.joinToString(prefix = "{ ", postfix = " }", separator = "; ") {
            "readonly ${jsProperty(it.name)}: ${it.domType}"
        }
    }

    /** Programmatic model references become ordinary runtime method/argument dispatches. */
    private fun rewriteProgrammaticActions(content: String): String {
        val calls = PROGRAMMATIC_ACTION_CALL.replace(content) { match ->
            val args = splitActionArguments(match.groupValues[3]).filterNot { it == "ctx" }.joinToString(", ")
            "ctx.dispatch(${jsString(match.groupValues[1])}, ${jsString(match.groupValues[2])}, [$args]"
        }
        return PROGRAMMATIC_ACTION_REF.replace(calls) { match ->
            "ctx.dispatch(${jsString(match.groupValues[1])}, ${jsString(match.groupValues[2])}"
        }
    }

    private fun clientHandlerNames(nodes: List<Node>): Set<String> {
        val names = linkedSetOf<String>()
        fun walk(list: List<Node>) {
            for (node in list) when (node) {
                is ElementNode -> {
                    node.attributes.forEach { attribute ->
                        if (attribute !is StaticAttribute || !attribute.name.startsWith("on") || attribute.name.length < 4) return@forEach
                        val value = attribute.value?.takeIf { parts -> parts.all { it is AttrText } }
                            ?.joinToString("") { (it as AttrText).value } ?: return@forEach
                        HANDLER_CALL.find(value)?.groupValues?.get(1)?.let(names::add)
                    }
                    walk(node.children)
                }
                is ForNode -> walk(node.children)
                is IfNode -> {
                    node.branches.forEach { walk(it.children) }
                    node.elseChildren?.let(::walk)
                }
                else -> Unit
            }
        }
        walk(nodes)
        return names
    }

    private fun hasEventAttribute(nodes: List<Node>): Boolean {
        for (node in nodes) when (node) {
            is ElementNode -> {
                if (node.attributes.any { it is EventAttribute } || hasEventAttribute(node.children)) return true
            }
            is ForNode -> if (hasEventAttribute(node.children)) return true
            is IfNode -> {
                if (node.branches.any { hasEventAttribute(it.children) }) return true
                if (node.elseChildren?.let(::hasEventAttribute) == true) return true
            }
            else -> Unit
        }
        return false
    }

    private fun dedent(content: String): List<String> {
        val lines = content.lines().dropWhile { it.isBlank() }.dropLastWhile { it.isBlank() }
        val common = lines.filter { it.isNotBlank() }
            .minOfOrNull { line -> line.takeWhile { it == ' ' || it == '\t' }.length } ?: 0
        return lines.map { if (it.isBlank()) "" else it.drop(common) }
    }

    private fun staticString(attrs: List<Attribute>, name: String): String? {
        val attr = attrs.filterIsInstance<StaticAttribute>().firstOrNull { it.name == name } ?: return null
        val value = attr.value ?: return null
        if (!value.all { it is AttrText }) return null
        return value.joinToString("") { (it as AttrText).value }
    }

    private fun jsProperty(name: String): String = if (JS_IDENTIFIER.matches(name)) name else jsString(name)

    private fun jsString(value: String): String =
        "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

    private companion object {
        private val CLIENT_IMPORT = Regex(
            "(?m)^[\\t ]*import\\s+(?:type\\s+)?(?:[\\s\\S]*?\\s+from\\s+)?[\"'][^\"']+[\"']\\s*;?[\\t ]*(?:\\r?\\n|$)",
        )
        private val HANDLER_CALL = Regex("^\\s*([A-Za-z_$][A-Za-z0-9_$]*)\\s*\\(")
        private val PROGRAMMATIC_ACTION_CALL = Regex(
            "ctx\\.dispatch\\(\\s*([A-Za-z_$][A-Za-z0-9_$]*)\\.([A-Za-z_$][A-Za-z0-9_$]*)\\s*\\(([^()]*)\\)",
        )
        private val PROGRAMMATIC_ACTION_REF = Regex(
            "ctx\\.dispatch\\(\\s*([A-Za-z_$][A-Za-z0-9_$]*)\\.([A-Za-z_$][A-Za-z0-9_$]*)",
        )
        private val JS_IDENTIFIER = Regex("[A-Za-z_$][A-Za-z0-9_$]*")
        private val DOM_TYPES = mapOf(
            "a" to "HTMLAnchorElement",
            "audio" to "HTMLAudioElement",
            "button" to "HTMLButtonElement",
            "canvas" to "HTMLCanvasElement",
            "form" to "HTMLFormElement",
            "iframe" to "HTMLIFrameElement",
            "img" to "HTMLImageElement",
            "input" to "HTMLInputElement",
            "select" to "HTMLSelectElement",
            "textarea" to "HTMLTextAreaElement",
            "video" to "HTMLVideoElement",
        )
    }
}
