package bosca.server

/**
 * Standard HTTP header name constants used throughout the server framework.
 *
 * Provides compile-time safe references to commonly used HTTP header names,
 * avoiding string literals scattered across the codebase.
 */
object HttpHeaders {
    const val Accept = "Accept"
    const val AcceptCharset = "Accept-Charset"
    const val AcceptEncoding = "Accept-Encoding"
    const val AcceptLanguage = "Accept-Language"
    const val AcceptRanges = "Accept-Ranges"
    const val AccessControlAllowCredentials = "Access-Control-Allow-Credentials"
    const val AccessControlAllowHeaders = "Access-Control-Allow-Headers"
    const val AccessControlAllowMethods = "Access-Control-Allow-Methods"
    const val AccessControlAllowOrigin = "Access-Control-Allow-Origin"
    const val AccessControlExposeHeaders = "Access-Control-Expose-Headers"
    const val AccessControlMaxAge = "Access-Control-Max-Age"
    const val AccessControlRequestHeaders = "Access-Control-Request-Headers"
    const val AccessControlRequestMethod = "Access-Control-Request-Method"
    const val Authorization = "Authorization"
    const val CacheControl = "Cache-Control"
    const val Connection = "Connection"
    const val ContentDisposition = "Content-Disposition"
    const val ContentEncoding = "Content-Encoding"
    const val ContentLength = "Content-Length"
    const val ContentRange = "Content-Range"
    const val ContentType = "Content-Type"
    const val Cookie = "Cookie"
    const val Date = "Date"
    const val ETag = "ETag"
    const val Expires = "Expires"
    const val Forwarded = "Forwarded"
    const val Host = "Host"
    const val IfMatch = "If-Match"
    const val IfModifiedSince = "If-Modified-Since"
    const val IfNoneMatch = "If-None-Match"
    const val IfUnmodifiedSince = "If-Unmodified-Since"
    const val LastModified = "Last-Modified"
    const val Location = "Location"
    const val Origin = "Origin"
    const val Pragma = "Pragma"
    const val Range = "Range"
    const val Referer = "Referer"
    const val RetryAfter = "Retry-After"
    const val SecWebSocketAccept = "Sec-WebSocket-Accept"
    const val SecWebSocketKey = "Sec-WebSocket-Key"
    const val SecWebSocketProtocol = "Sec-WebSocket-Protocol"
    const val SecWebSocketVersion = "Sec-WebSocket-Version"
    const val Server = "Server"
    const val SetCookie = "Set-Cookie"
    const val TransferEncoding = "Transfer-Encoding"
    const val Upgrade = "Upgrade"
    const val UserAgent = "User-Agent"
    const val Vary = "Vary"
    const val XForwardedFor = "X-Forwarded-For"
    const val XForwardedHost = "X-Forwarded-Host"
    const val XForwardedProto = "X-Forwarded-Proto"
    const val XForwardedPort = "X-Forwarded-Port"
    const val XRealIp = "X-Real-IP"
    const val XRequestId = "X-Request-Id"
    const val XSessionID = "X-BA-Session-ID"
    const val WWWAuthenticate = "WWW-Authenticate"
}
