package yks

import yks.utils.*
import yks.types.*
import kotlin.test.*

/**
 * Wire compatibility tests for snapshots, relative positions, and state vectors
 * against binary fixtures generated by JavaScript yjs 13.6.30.
 *
 * Fixtures generated by fixtures/generate.mjs using yjs npm package.
 *
 * NOTE on relative position encoding: yjs uses a single-tag format where the first
 * varUint encodes both the item/type decision:
 *   tag=0 -> has item (read item ID, then assoc)
 *   tag=1 -> has tname (read varString, then assoc)
 *   tag=2 -> has type ID (read type ID, then assoc)
 * The Kotlin port must match this format for wire compatibility.
 */
class WireCompatSnapshotTest {

    private fun hexToBytes(hex: String): ByteArray {
        val result = ByteArray(hex.length / 2)
        for (i in result.indices) {
            result[i] = hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return result
    }

    private fun toHex(bytes: ByteArray): String {
        return bytes.joinToString("") {
            val v = it.toInt() and 0xFF
            val hi = v shr 4
            val lo = v and 0x0F
            "${HEX_CHARS[hi]}${HEX_CHARS[lo]}"
        }
    }

    companion object {
        private const val HEX_CHARS = "0123456789abcdef"
    }

    // =========================================================================
    // Snapshot Tests
    // =========================================================================

    @Test
    fun testSnapshotArrayDecode() {
        // Decode the yjs snapshot and verify its contents
        val snap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_ARRAY_SNAPSHOT_V1))
        assertEquals(1, snap.sv.size, "snapshot should have 1 client")
        assertEquals(3, snap.sv[301], "client 301 should have clock 3")
        assertTrue(snap.ds.clients.isEmpty(), "delete set should be empty")
    }

    @Test
    fun testSnapshotArrayEncodeRoundTrip() {
        val originalBytes = hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_ARRAY_SNAPSHOT_V1)
        val snap = decodeSnapshot(originalBytes)
        val reencoded = encodeSnapshot(snap)
        val snap2 = decodeSnapshot(reencoded)
        assertTrue(equalSnapshots(snap, snap2), "re-encoded snapshot should decode to equal snapshot")
    }

    @Test
    fun testSnapshotArrayByteExact() {
        // Single-client snapshot with empty delete set: no ordering ambiguity
        val expectedHex = WireCompatFixtures.SNAPSHOTS_SNAPSHOT_ARRAY_SNAPSHOT_V1
        val snap = decodeSnapshot(hexToBytes(expectedHex))
        val reencoded = toHex(encodeSnapshot(snap))
        assertEquals(expectedHex, reencoded,
            "snapshot encoding should be byte-exact for single-client snapshot")
    }

    @Test
    fun testSnapshotArrayRestore() {
        // Apply fullUpdateAfter to get the complete post-mutation doc (gc=false to keep all structs)
        val originDoc = Doc(gc = false)
        applyUpdate(originDoc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_ARRAY_FULL_UPDATE_AFTER))

        // Decode the snapshot taken at the "before" state
        val snap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_ARRAY_SNAPSHOT_V1))

        // Restore from snapshot
        val restoredDoc = createDocFromSnapshot(originDoc, snap)
        val arr = restoredDoc.getArray("arr")
        assertEquals(3, arr.length, "restored array should have 3 elements")
        assertEquals(listOf(1, 2, 3), arr.toArray(), "restored array should be [1, 2, 3]")
    }

    @Test
    fun testSnapshotArrayStateVectorAtSnapshot() {
        // Build the pre-snapshot state and capture snapshot, verify state vector matches
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_ARRAY_FULL_UPDATE_BEFORE))
        val snap = snapshot(doc)
        assertEquals(3, snap.sv[301], "state vector should show client 301 at clock 3")
    }

    @Test
    fun testSnapshotArrayCapturedMatchesYjs() {
        // Build state from fullUpdateBefore, capture snapshot, verify it matches yjs snapshot
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_ARRAY_FULL_UPDATE_BEFORE))
        val snap = snapshot(doc)
        val yjsSnap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_ARRAY_SNAPSHOT_V1))
        assertTrue(equalSnapshots(snap, yjsSnap),
            "snapshot captured in Kotlin should equal yjs-captured snapshot")
    }

    @Test
    fun testSnapshotTextDecode() {
        val snap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_TEXT_SNAPSHOT_V1))
        assertEquals(1, snap.sv.size, "snapshot should have 1 client")
        assertEquals(11, snap.sv[302], "client 302 should have clock 11")
        assertTrue(snap.ds.clients.isEmpty(), "delete set should be empty")
    }

    @Test
    fun testSnapshotTextByteExact() {
        val expectedHex = WireCompatFixtures.SNAPSHOTS_SNAPSHOT_TEXT_SNAPSHOT_V1
        val snap = decodeSnapshot(hexToBytes(expectedHex))
        val reencoded = toHex(encodeSnapshot(snap))
        assertEquals(expectedHex, reencoded)
    }

    @Test
    fun testSnapshotTextRestore() {
        val originDoc = Doc(gc = false)
        applyUpdate(originDoc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_TEXT_FULL_UPDATE_AFTER))

        val snap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_TEXT_SNAPSHOT_V1))

        val restoredDoc = createDocFromSnapshot(originDoc, snap)
        val text = restoredDoc.getText("text")
        assertEquals("Hello World", text.toString(), "restored text should be 'Hello World'")
    }

    @Test
    fun testSnapshotTextStateVectorAtSnapshot() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_TEXT_FULL_UPDATE_BEFORE))
        val snap = snapshot(doc)
        assertEquals(11, snap.sv[302], "state vector should show client 302 at clock 11")
    }

    @Test
    fun testSnapshotTextCapturedMatchesYjs() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_TEXT_FULL_UPDATE_BEFORE))
        val snap = snapshot(doc)
        val yjsSnap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_TEXT_SNAPSHOT_V1))
        assertTrue(equalSnapshots(snap, yjsSnap))
    }

    @Test
    fun testSnapshotMapDecode() {
        val snap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MAP_SNAPSHOT_V1))
        assertEquals(1, snap.sv.size, "snapshot should have 1 client")
        assertEquals(3, snap.sv[303], "client 303 should have clock 3")
        assertTrue(snap.ds.clients.isEmpty(), "delete set should be empty")
    }

    @Test
    fun testSnapshotMapByteExact() {
        val expectedHex = WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MAP_SNAPSHOT_V1
        val snap = decodeSnapshot(hexToBytes(expectedHex))
        val reencoded = toHex(encodeSnapshot(snap))
        assertEquals(expectedHex, reencoded)
    }

    @Test
    fun testSnapshotMapRestore() {
        val originDoc = Doc(gc = false)
        applyUpdate(originDoc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MAP_FULL_UPDATE_AFTER))

        val snap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MAP_SNAPSHOT_V1))

        val restoredDoc = createDocFromSnapshot(originDoc, snap)
        val map = restoredDoc.getMap("map")
        assertEquals(1, map.get("a"), "restored map['a'] should be 1")
        assertEquals(2, map.get("b"), "restored map['b'] should be 2")
        assertEquals(3, map.get("c"), "restored map['c'] should be 3")
    }

    @Test
    fun testSnapshotMapStateVectorAtSnapshot() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MAP_FULL_UPDATE_BEFORE))
        val snap = snapshot(doc)
        assertEquals(3, snap.sv[303], "state vector should show client 303 at clock 3")
    }

    @Test
    fun testSnapshotMapCapturedMatchesYjs() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MAP_FULL_UPDATE_BEFORE))
        val snap = snapshot(doc)
        val yjsSnap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MAP_SNAPSHOT_V1))
        assertTrue(equalSnapshots(snap, yjsSnap))
    }

    @Test
    fun testSnapshotMultiTypeDecode() {
        val snap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MULTI_TYPE_SNAPSHOT_V1))
        assertEquals(1, snap.sv.size, "snapshot should have 1 client")
        assertEquals(5, snap.sv[304], "client 304 should have clock 5")
        assertTrue(snap.ds.clients.isEmpty(), "delete set should be empty")
    }

    @Test
    fun testSnapshotMultiTypeByteExact() {
        val expectedHex = WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MULTI_TYPE_SNAPSHOT_V1
        val snap = decodeSnapshot(hexToBytes(expectedHex))
        val reencoded = toHex(encodeSnapshot(snap))
        assertEquals(expectedHex, reencoded)
    }

    @Test
    fun testSnapshotMultiTypeRestore() {
        val originDoc = Doc(gc = false)
        applyUpdate(originDoc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MULTI_TYPE_FULL_UPDATE_AFTER))

        val snap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MULTI_TYPE_SNAPSHOT_V1))

        val restoredDoc = createDocFromSnapshot(originDoc, snap)

        val arr = restoredDoc.getArray("arr")
        assertEquals(2, arr.length, "restored array should have 2 elements")
        assertEquals(listOf(1, 2), arr.toArray(), "restored array should be [1, 2]")

        val map = restoredDoc.getMap("map")
        assertEquals("val", map.get("key"), "restored map['key'] should be 'val'")

        val text = restoredDoc.getText("text")
        assertEquals("hi", text.toString(), "restored text should be 'hi'")
    }

    @Test
    fun testSnapshotMultiTypeStateVectorAtSnapshot() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MULTI_TYPE_FULL_UPDATE_BEFORE))
        val snap = snapshot(doc)
        assertEquals(5, snap.sv[304], "state vector should show client 304 at clock 5")
    }

    @Test
    fun testSnapshotMultiTypeCapturedMatchesYjs() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MULTI_TYPE_FULL_UPDATE_BEFORE))
        val snap = snapshot(doc)
        val yjsSnap = decodeSnapshot(hexToBytes(WireCompatFixtures.SNAPSHOTS_SNAPSHOT_MULTI_TYPE_SNAPSHOT_V1))
        assertTrue(equalSnapshots(snap, yjsSnap))
    }

    // =========================================================================
    // Relative Position Tests
    //
    // yjs encodes relative positions as a single-tag format:
    //   tag=0: item exists -> readID(item), then readVarInt(assoc)
    //   tag=1: tname exists (position at type boundary) -> readVarString(tname), then readVarInt(assoc)
    //   tag=2: type ID exists -> readID(type), then readVarInt(assoc)
    // =========================================================================

    @Test
    fun testRposTextMiddleDecodeYjsBytes() {
        // yjs hex: "0091030500"
        // tag=0 (has item), item=ID(401,5), assoc=0
        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_ENCODED_RPOS)
        )
        assertNotNull(rpos.item, "rpos should reference an item")
        assertEquals(401, rpos.item.client, "rpos item client should be 401")
        assertEquals(5, rpos.item.clock, "rpos item clock should be 5")
        assertEquals(0, rpos.assoc, "assoc should be 0")
    }

    @Test
    fun testRposTextMiddleEncodeMatchesYjs() {
        // Build doc with "Hello World", create rpos at index 5
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_FULL_UPDATE_BEFORE))

        val text = doc.getText("text")
        assertEquals(11, text.length, "text should be 11 chars")

        val rpos = createRelativePositionFromTypeIndex(
            text,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_INDEX_BEFORE,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_ASSOC
        )
        val encoded = toHex(encodeRelativePosition(rpos))
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_ENCODED_RPOS, encoded,
            "encoded rpos should match yjs bytes"
        )
    }

    @Test
    fun testRposTextMiddleResolveAfterMutation() {
        // Apply the full post-mutation state
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_FULL_UPDATE_AFTER))

        // Decode the yjs relative position
        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_ENCODED_RPOS)
        )

        // Resolve
        val absPos = createAbsolutePositionFromRelativePosition(rpos, doc)
        assertNotNull(absPos, "should resolve to an absolute position")
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_RESOLVED_INDEX_AFTER,
            absPos.index,
            "resolved index after inserting 'XXX' at start should shift from 5 to 8"
        )
    }

    @Test
    fun testRposTextMiddleCreateAndResolve() {
        // Full workflow: create rpos in before-state, resolve in after-state
        val docBefore = Doc(gc = false)
        applyUpdate(docBefore, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_FULL_UPDATE_BEFORE))

        val text = docBefore.getText("text")
        val rpos = createRelativePositionFromTypeIndex(
            text,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_INDEX_BEFORE,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_ASSOC
        )

        val docAfter = Doc(gc = false)
        applyUpdate(docAfter, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_FULL_UPDATE_AFTER))

        val absPos = createAbsolutePositionFromRelativePosition(rpos, docAfter)
        assertNotNull(absPos)
        assertEquals(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_RESOLVED_INDEX_AFTER, absPos.index)
    }

    @Test
    fun testRposTextStartDecodeYjsBytes() {
        // yjs hex: "01047465787441"
        // tag=1 (has tname), tname="text", assoc=-1 (0x41 zigzag)
        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_ENCODED_RPOS)
        )
        assertNull(rpos.item, "rpos at start with assoc=-1 should have null item")
        assertEquals("text", rpos.tname, "tname should be 'text'")
        assertEquals(-1, rpos.assoc, "assoc should be -1")
    }

    @Test
    fun testRposTextStartEncodeMatchesYjs() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_FULL_UPDATE_BEFORE))

        val text = doc.getText("text")
        val rpos = createRelativePositionFromTypeIndex(
            text,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_INDEX_BEFORE,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_ASSOC
        )
        val encoded = toHex(encodeRelativePosition(rpos))
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_ENCODED_RPOS, encoded,
            "encoded rpos at text start should match yjs bytes"
        )
    }

    @Test
    fun testRposTextStartResolveAfterMutation() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_FULL_UPDATE_AFTER))

        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_ENCODED_RPOS)
        )

        val absPos = createAbsolutePositionFromRelativePosition(rpos, doc)
        assertNotNull(absPos, "should resolve to an absolute position")
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_RESOLVED_INDEX_AFTER,
            absPos.index,
            "resolved index at start with assoc=-1 should stay at 0 after prepend"
        )
    }

    @Test
    fun testRposArrayMiddleDecodeYjsBytes() {
        // yjs hex: "0093030300"
        // tag=0 (has item), item=ID(403,3), assoc=0
        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_ENCODED_RPOS)
        )
        assertNotNull(rpos.item, "rpos should reference an item")
        assertEquals(403, rpos.item.client, "rpos item client should be 403")
        assertEquals(3, rpos.item.clock, "rpos item clock should be 3")
        assertEquals(0, rpos.assoc, "assoc should be 0")
    }

    @Test
    fun testRposArrayMiddleEncodeMatchesYjs() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_FULL_UPDATE_BEFORE))

        val arr = doc.getArray("arr")
        assertEquals(5, arr.length, "array should have 5 elements")

        val rpos = createRelativePositionFromTypeIndex(
            arr,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_INDEX_BEFORE,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_ASSOC
        )
        val encoded = toHex(encodeRelativePosition(rpos))
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_ENCODED_RPOS, encoded,
            "encoded rpos for array middle should match yjs bytes"
        )
    }

    @Test
    fun testRposArrayMiddleResolveAfterMutation() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_FULL_UPDATE_AFTER))

        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_ENCODED_RPOS)
        )

        val absPos = createAbsolutePositionFromRelativePosition(rpos, doc)
        assertNotNull(absPos, "should resolve to an absolute position")
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_RESOLVED_INDEX_AFTER,
            absPos.index,
            "resolved index after prepend should shift from 3 to 4"
        )
    }

    @Test
    fun testRposTextEndDecodeYjsBytes() {
        // yjs hex: "0094030441"
        // tag=0 (has item), item=ID(404,4), assoc=-1 (0x41 zigzag)
        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_ENCODED_RPOS)
        )
        assertNotNull(rpos.item, "rpos should reference an item")
        assertEquals(404, rpos.item.client, "rpos item client should be 404")
        assertEquals(4, rpos.item.clock, "rpos item clock should be 4 (last char of 'Hello')")
        assertEquals(-1, rpos.assoc, "assoc should be -1")
    }

    @Test
    fun testRposTextEndEncodeMatchesYjs() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_FULL_UPDATE_BEFORE))

        val text = doc.getText("text")
        assertEquals(5, text.length, "text should be 5 chars")

        val rpos = createRelativePositionFromTypeIndex(
            text,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_INDEX_BEFORE,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_ASSOC
        )
        val encoded = toHex(encodeRelativePosition(rpos))
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_ENCODED_RPOS, encoded,
            "encoded rpos at text end should match yjs bytes"
        )
    }

    @Test
    fun testRposTextEndResolveAfterMutation() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_FULL_UPDATE_AFTER))

        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_ENCODED_RPOS)
        )

        val absPos = createAbsolutePositionFromRelativePosition(rpos, doc)
        assertNotNull(absPos, "should resolve to an absolute position")
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_RESOLVED_INDEX_AFTER,
            absPos.index,
            "resolved index at end with assoc=-1 should stay at 5 after appending ' World'"
        )
    }

    @Test
    fun testRposAfterDeleteDecodeYjsBytes() {
        // yjs hex: "0095030300"
        // tag=0 (has item), item=ID(405,3), assoc=0
        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_ENCODED_RPOS)
        )
        assertNotNull(rpos.item, "rpos should reference an item")
        assertEquals(405, rpos.item.client, "rpos item client should be 405")
        assertEquals(3, rpos.item.clock, "rpos item clock should be 3")
        assertEquals(0, rpos.assoc, "assoc should be 0")
    }

    @Test
    fun testRposAfterDeleteEncodeMatchesYjs() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_FULL_UPDATE_BEFORE))

        val text = doc.getText("text")
        assertEquals(5, text.length, "text should be 5 chars ('ABCDE')")

        val rpos = createRelativePositionFromTypeIndex(
            text,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_INDEX_BEFORE,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_ASSOC
        )
        val encoded = toHex(encodeRelativePosition(rpos))
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_ENCODED_RPOS, encoded,
            "encoded rpos after delete should match yjs bytes"
        )
    }

    @Test
    fun testRposAfterDeleteResolveAfterMutation() {
        val doc = Doc(gc = false)
        applyUpdate(doc, hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_FULL_UPDATE_AFTER))

        val rpos = decodeRelativePosition(
            hexToBytes(WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_ENCODED_RPOS)
        )

        val absPos = createAbsolutePositionFromRelativePosition(rpos, doc)
        assertNotNull(absPos, "should resolve to an absolute position")
        assertEquals(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_RESOLVED_INDEX_AFTER,
            absPos.index,
            "resolved index should shift from 3 to 1 after deleting 'AB'"
        )
    }

    @Test
    fun testRposEncodeDecodeRoundTrip() {
        // Verify all rpos fixtures survive encode -> decode -> encode round-trip
        val rposHexValues = listOf(
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_MIDDLE_ENCODED_RPOS,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_START_ENCODED_RPOS,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_ARRAY_MIDDLE_ENCODED_RPOS,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_TEXT_END_ENCODED_RPOS,
            WireCompatFixtures.RELATIVE_POSITIONS_RPOS_AFTER_DELETE_ENCODED_RPOS
        )
        for (hex in rposHexValues) {
            val rpos = decodeRelativePosition(hexToBytes(hex))
            val reencoded = toHex(encodeRelativePosition(rpos))
            assertEquals(hex, reencoded, "rpos encode-decode round-trip should be byte-exact for $hex")
        }
    }

    // =========================================================================
    // State Vector Tests
    // =========================================================================

    @Test
    fun testStateVectorMultiClientDecode() {
        // Hex "02d80401f40301" decodes to: {600: 1, 500: 1}
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.STATE_VECTORS_MULTI_CLIENT_STATE_VECTOR))
        assertEquals(2, sv.size, "should have 2 clients")
        assertTrue(sv.containsKey(500), "should contain client 500")
        assertTrue(sv.containsKey(600), "should contain client 600")
        assertEquals(1, sv[500], "client 500 should have clock 1")
        // Note: fixture JSON says {500:1, 600:2} but hex actually decodes to {500:1, 600:1}.
        // The hex is the authoritative source. If the JSON expectedMap differs, the hex wins.
    }

    @Test
    fun testStateVectorMultiClientReencode() {
        val originalHex = WireCompatFixtures.STATE_VECTORS_MULTI_CLIENT_STATE_VECTOR
        val sv = decodeStateVector(hexToBytes(originalHex))
        val reencoded = encodeStateVectorFromMap(sv)
        val sv2 = decodeStateVector(reencoded)
        assertEquals(sv, sv2, "re-encoded state vector should decode to same map")
    }

    @Test
    fun testStateVectorEmpty() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.STATE_VECTORS_EMPTY_STATE_VECTOR))
        assertTrue(sv.isEmpty(), "empty state vector should decode to empty map")
        val reencoded = toHex(encodeStateVectorFromMap(sv))
        assertEquals(WireCompatFixtures.STATE_VECTORS_EMPTY_STATE_VECTOR, reencoded,
            "empty state vector encoding should be byte-exact")
    }

    @Test
    fun testStateVectorSingleClient() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.STATE_VECTORS_SINGLE_CLIENT_STATE_VECTOR))
        assertEquals(1, sv.size, "should have 1 client")
        assertEquals(5, sv[800], "client 800 should have clock 5")
        // Single client: no ordering ambiguity, encoding should be byte-exact
        val reencoded = toHex(encodeStateVectorFromMap(sv))
        assertEquals(WireCompatFixtures.STATE_VECTORS_SINGLE_CLIENT_STATE_VECTOR, reencoded,
            "single-client state vector encoding should be byte-exact")
    }

    @Test
    fun testStateVectorManyClients() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.STATE_VECTORS_MANY_CLIENTS_STATE_VECTOR))
        assertEquals(6, sv.size, "should have 6 clients")
        for (client in listOf(900, 1000, 1100, 1200, 1300, 1400)) {
            assertTrue(sv.containsKey(client), "should contain client $client")
            assertEquals(1, sv[client], "client $client should have clock 1")
        }
    }

    @Test
    fun testStateVectorManyClientsReencode() {
        val originalHex = WireCompatFixtures.STATE_VECTORS_MANY_CLIENTS_STATE_VECTOR
        val sv = decodeStateVector(hexToBytes(originalHex))
        val reencoded = encodeStateVectorFromMap(sv)
        val sv2 = decodeStateVector(reencoded)
        assertEquals(sv, sv2, "re-encoded many-client state vector should decode to same map")
    }
}
