package yks

import yks.utils.*
import yks.types.*
import kotlin.test.*

/**
 * Wire compatibility tests for V2 encoding format against binary fixtures
 * generated by JavaScript yjs. Each test decodes a V2 update produced by yjs
 * and verifies the resulting state. Encode tests verify that yks produces
 * byte-identical V2 output when constructing the same document.
 *
 * Fixtures generated by fixtures/generate.mjs using yjs npm package.
 */
class WireCompatV2Test {

    private fun hexToBytes(hex: String): ByteArray {
        val result = ByteArray(hex.length / 2)
        for (i in result.indices) {
            result[i] = hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return result
    }

    private fun toHex(bytes: ByteArray): String {
        return bytes.joinToString("") {
            val v = it.toInt() and 0xFF
            val hi = v shr 4
            val lo = v and 0x0F
            "${HEX_CHARS[hi]}${HEX_CHARS[lo]}"
        }
    }

    companion object {
        private const val HEX_CHARS = "0123456789abcdef"
    }

    private fun applyFixtureV2(updateV2Hex: String): Doc {
        val doc = Doc()
        val update = hexToBytes(updateV2Hex)
        applyUpdateV2(doc, update)
        return doc
    }

    // ==========================================================================
    // single_doc_v2 — Decode Tests
    // ==========================================================================

    @Test
    fun testDecodeV2ArrayInts() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_INTS_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(3, arr.length)
        assertEquals(listOf(1, 2, 3), arr.toArray())
    }

    @Test
    fun testDecodeV2MapStrings() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MAP_STRINGS_UPDATE_V2)
        val map = doc.getMap("map")
        assertEquals("value1", map.get("key1"))
        assertEquals("value2", map.get("key2"))
    }

    @Test
    fun testDecodeV2TextSimple() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_SIMPLE_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("Hello World", text.toString())
    }

    @Test
    fun testDecodeV2ArrayMixedTypes() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_MIXED_TYPES_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(5, arr.length)
        assertEquals(42, arr.get(0))
        assertEquals("hello", arr.get(1))
        assertEquals(true, arr.get(2))
        assertEquals(false, arr.get(3))
        assertNull(arr.get(4))
    }

    @Test
    fun testDecodeV2NestedMapArray() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_NESTED_MAP_ARRAY_UPDATE_V2)
        val root = doc.getMap("root")
        val list = root.get("list") as YArray
        assertEquals(listOf(1, 2, 3), list.toArray())
    }

    @Test
    fun testDecodeV2EmptyDoc() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_EMPTY_DOC_UPDATE_V2)
        // Empty doc should have no meaningful shared types with content
        val sv = encodeStateVector(doc)
        val svHex = toHex(sv)
        assertEquals("00", svHex)
    }

    @Test
    fun testDecodeV2ArrayLarge() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_LARGE_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(100, arr.length)
        val expected = (0 until 100).toList()
        assertEquals(expected, arr.toArray())
    }

    @Test
    fun testDecodeV2MapLarge() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MAP_LARGE_UPDATE_V2)
        val map = doc.getMap("map")
        for (i in 0 until 50) {
            val key = "k${i.toString().padStart(2, '0')}"
            assertEquals("v$i", map.get(key))
        }
    }

    @Test
    fun testDecodeV2TextLong() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_LONG_UPDATE_V2)
        val text = doc.getText("text")
        val expected = "A".repeat(1000)
        assertEquals(expected, text.toString())
    }

    @Test
    fun testDecodeV2TextUnicodeEmoji() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_EMOJI_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("Hello \uD83C\uDF0D\uD83C\uDF89 World", text.toString())
    }

    @Test
    fun testDecodeV2TextUnicodeCjk() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_CJK_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("\u4F60\u597D\u4E16\u754C\u3053\u3093\u306B\u3061\u306F", text.toString())
    }

    @Test
    fun testDecodeV2TextUnicodeArabic() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_ARABIC_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("\u0645\u0631\u062D\u0628\u0627 \u0628\u0627\u0644\u0639\u0627\u0644\u0645", text.toString())
    }

    @Test
    fun testDecodeV2Nested3Levels() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_NESTED_3_LEVELS_UPDATE_V2)
        val root = doc.getMap("root")
        val mid = root.get("mid") as YMap
        val inner = mid.get("inner") as YArray
        assertEquals(listOf(1, 2, 3), inner.toArray())
    }

    @Test
    fun testDecodeV2ArrayFloats() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_FLOATS_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(5, arr.length)
        val values = arr.toArray()
        assertEquals(1.5, values[0])
        assertEquals(-2.7, (values[1] as Number).toDouble(), 0.0001)
        assertEquals(0, values[2])
        assertEquals(3.14159, (values[3] as Number).toDouble(), 0.00001)
        assertEquals(-0.001, (values[4] as Number).toDouble(), 0.0001)
    }

    @Test
    fun testDecodeV2ArrayLargeInts() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_LARGE_INTS_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(5, arr.length)
        val values = arr.toArray()
        assertEquals(0, values[0])
        assertEquals(-1, values[1])
        assertEquals(2147483647, values[2])
        // -2147483648 is written as float32 by yjs (tag 124), decoded as Double
        assertEquals(-2147483648.0, (values[3] as Number).toDouble(), 0.0)
        assertEquals(1000000, values[4])
    }

    @Test
    fun testDecodeV2MultiTypesSameDoc() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MULTI_TYPES_SAME_DOC_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(listOf(1, 2), arr.toArray())
        val map = doc.getMap("map")
        assertEquals("val", map.get("key"))
        val text = doc.getText("text")
        assertEquals("hello", text.toString())
    }

    @Test
    fun testDecodeV2MapNestedTypes() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MAP_NESTED_TYPES_UPDATE_V2)
        val map = doc.getMap("map")
        val list = map.get("list") as YArray
        assertEquals(listOf("a", "b"), list.toArray())
        val nested = map.get("nested") as YMap
        assertEquals(42, nested.get("x"))
    }

    @Test
    fun testDecodeV2ArraySingleItem() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_SINGLE_ITEM_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(1, arr.length)
        assertEquals(42, arr.get(0))
    }

    @Test
    fun testDecodeV2MapSingleEntry() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MAP_SINGLE_ENTRY_UPDATE_V2)
        val map = doc.getMap("map")
        assertEquals("entry", map.get("only"))
    }

    @Test
    fun testDecodeV2TextSingleChar() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_SINGLE_CHAR_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("X", text.toString())
    }

    @Test
    fun testDecodeV2ArrayNestedArrays() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_NESTED_ARRAYS_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(2, arr.length)
        val inner1 = arr.get(0) as YArray
        assertEquals(listOf(1, 2), inner1.toArray())
        val inner2 = arr.get(1) as YArray
        assertEquals(listOf(3, 4), inner2.toArray())
    }

    @Test
    fun testDecodeV2MapBooleanNullValues() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MAP_BOOLEAN_NULL_VALUES_UPDATE_V2)
        val map = doc.getMap("map")
        assertEquals(true, map.get("t"))
        assertEquals(false, map.get("f"))
        assertNull(map.get("n"))
        assertEquals(0, map.get("zero"))
        assertEquals("", map.get("empty"))
    }

    @Test
    fun testDecodeV2TextMultiline() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_MULTILINE_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("line1\nline2\nline3", text.toString())
    }

    // ==========================================================================
    // single_doc_v2 — XML Decode Tests
    // ==========================================================================

    @Test
    fun testDecodeV2XmlSimpleElement() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_XML_SIMPLE_ELEMENT_UPDATE_V2)
        val frag = doc.getXmlFragment("content")
        val p = frag.toArray()[0] as YXmlElement
        assertEquals("paragraph", p.tag)
        assertEquals("Hello World", (p.toArray()[0] as YXmlText).toString())
    }

    @Test
    fun testDecodeV2XmlNestedElements() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_XML_NESTED_ELEMENTS_UPDATE_V2)
        val frag = doc.getXmlFragment("content")
        val div = frag.toArray()[0] as YXmlElement
        assertEquals("div", div.tag)
        val h1 = div.toArray()[0] as YXmlElement
        assertEquals("heading", h1.tag)
        assertEquals("Title", (h1.toArray()[0] as YXmlText).toString())
        val p = div.toArray()[1] as YXmlElement
        assertEquals("paragraph", p.tag)
        assertEquals("Body text", (p.toArray()[0] as YXmlText).toString())
    }

    @Test
    fun testDecodeV2XmlHook() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_XML_HOOK_UPDATE_V2)
        val frag = doc.getXmlFragment("content")
        val hook = frag.toArray()[0] as YXmlHook
        assertEquals("my-widget", hook.hookName)
        assertEquals("value", hook.get("config"))
    }

    @Test
    fun testDecodeV2XmlMultipleParagraphs() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_XML_MULTIPLE_PARAGRAPHS_UPDATE_V2)
        val frag = doc.getXmlFragment("content")
        val children = frag.toArray()
        assertEquals(3, children.size)
        assertEquals("First paragraph", ((children[0] as YXmlElement).toArray()[0] as YXmlText).toString())
        assertEquals("Second paragraph", ((children[1] as YXmlElement).toArray()[0] as YXmlText).toString())
        assertEquals("Third paragraph", ((children[2] as YXmlElement).toArray()[0] as YXmlText).toString())
    }

    @Test
    fun testDecodeV2XmlWithMapsAndArrays() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_XML_WITH_MAPS_AND_ARRAYS_UPDATE_V2)
        val frag = doc.getXmlFragment("content")
        val p = frag.toArray()[0] as YXmlElement
        assertEquals("paragraph", p.tag)
        assertEquals("Document text", (p.toArray()[0] as YXmlText).toString())
        assertEquals("My Doc", doc.getMap("meta").get("title"))
        assertEquals(listOf("tag1", "tag2"), doc.getArray("tags").toArray())
    }

    @Test
    fun testDecodeV2XmlSimpleElementRoundTrip() {
        val update = hexToBytes(WireCompatFixtures.SINGLE_DOC_V2_XML_SIMPLE_ELEMENT_UPDATE_V2)
        val doc = Doc()
        applyUpdateV2(doc, update)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_XML_SIMPLE_ELEMENT_UPDATE_V2, reencoded)
    }

    @Test
    fun testDecodeV2XmlNestedElementsRoundTrip() {
        val update = hexToBytes(WireCompatFixtures.SINGLE_DOC_V2_XML_NESTED_ELEMENTS_UPDATE_V2)
        val doc = Doc()
        applyUpdateV2(doc, update)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_XML_NESTED_ELEMENTS_UPDATE_V2, reencoded)
    }

    @Test
    fun testDecodeV2XmlHookRoundTrip() {
        val update = hexToBytes(WireCompatFixtures.SINGLE_DOC_V2_XML_HOOK_UPDATE_V2)
        val doc = Doc()
        applyUpdateV2(doc, update)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_XML_HOOK_UPDATE_V2, reencoded)
    }

    // ==========================================================================
    // delete_ops_v2 — Decode Tests
    // ==========================================================================

    @Test
    fun testDecodeV2ArrayWithDelete() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_ARRAY_WITH_DELETE_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(3, arr.length)
        assertEquals(listOf("a", "d", "e"), arr.toArray())
    }

    @Test
    fun testDecodeV2MapWithDelete() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_MAP_WITH_DELETE_UPDATE_V2)
        val map = doc.getMap("map")
        assertEquals(1, map.get("a"))
        assertNull(map.get("b"))
        assertEquals(3, map.get("c"))
    }

    @Test
    fun testDecodeV2TextEditing() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_TEXT_EDITING_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("Hello, World", text.toString())
    }

    @Test
    fun testDecodeV2MapOverwrite() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_MAP_OVERWRITE_UPDATE_V2)
        val map = doc.getMap("map")
        assertEquals("value2", map.get("key"))
    }

    @Test
    fun testDecodeV2TextDeleteMiddle() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_MIDDLE_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("HelloWorld", text.toString())
    }

    @Test
    fun testDecodeV2TextDeleteStart() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_START_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("World", text.toString())
    }

    @Test
    fun testDecodeV2TextDeleteEnd() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_END_UPDATE_V2)
        val text = doc.getText("text")
        assertEquals("Hello", text.toString())
    }

    @Test
    fun testDecodeV2ArrayDeleteAll() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_ALL_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(0, arr.length)
        assertEquals(emptyList(), arr.toArray())
    }

    @Test
    fun testDecodeV2ArrayDeleteThenReadd() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_THEN_READD_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(3, arr.length)
        assertEquals(listOf(4, 5, 6), arr.toArray())
    }

    @Test
    fun testDecodeV2MapOverwriteChain() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_MAP_OVERWRITE_CHAIN_UPDATE_V2)
        val map = doc.getMap("map")
        assertEquals("v4", map.get("key"))
    }

    @Test
    fun testDecodeV2ArrayDeleteFirst() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_FIRST_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(2, arr.length)
        assertEquals(listOf("b", "c"), arr.toArray())
    }

    @Test
    fun testDecodeV2ArrayDeleteLast() {
        val doc = applyFixtureV2(WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_LAST_UPDATE_V2)
        val arr = doc.getArray("arr")
        assertEquals(2, arr.length)
        assertEquals(listOf("a", "b"), arr.toArray())
    }

    // ==========================================================================
    // single_doc_v2 — Encode Tests (byte-exact match with yjs V2 output)
    // ==========================================================================

    @Test
    fun testEncodeV2ArrayInts() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_INTS_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf(1, 2, 3))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_INTS_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_ints should match yjs")
    }

    @Test
    fun testEncodeV2MapStrings() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_MAP_STRINGS_CLIENT_ID
        val map = doc.getMap("map")
        map.set("key1", "value1")
        map.set("key2", "value2")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_MAP_STRINGS_UPDATE_V2
        assertEquals(expected, actual, "V2 encode map_strings should match yjs")
    }

    @Test
    fun testEncodeV2TextSimple() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_TEXT_SIMPLE_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "Hello World")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_TEXT_SIMPLE_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_simple should match yjs")
    }

    @Test
    fun testEncodeV2ArrayMixedTypes() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_MIXED_TYPES_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf(42, "hello", true, false, null))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_MIXED_TYPES_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_mixed_types should match yjs")
    }

    @Test
    fun testEncodeV2NestedMapArray() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_NESTED_MAP_ARRAY_CLIENT_ID
        val root = doc.getMap("root")
        val list = YArray()
        root.set("list", list)
        list.push(listOf(1, 2, 3))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_NESTED_MAP_ARRAY_UPDATE_V2
        assertEquals(expected, actual, "V2 encode nested_map_array should match yjs")
    }

    @Test
    fun testEncodeV2EmptyDoc() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_EMPTY_DOC_CLIENT_ID
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_EMPTY_DOC_UPDATE_V2
        assertEquals(expected, actual, "V2 encode empty_doc should match yjs")
    }

    @Test
    fun testEncodeV2ArrayLarge() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_LARGE_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push((0 until 100).toList())
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_LARGE_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_large should match yjs")
    }

    @Test
    fun testEncodeV2MapLarge() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_MAP_LARGE_CLIENT_ID
        val map = doc.getMap("map")
        for (i in 0 until 50) {
            val key = "k${i.toString().padStart(2, '0')}"
            map.set(key, "v$i")
        }
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_MAP_LARGE_UPDATE_V2
        assertEquals(expected, actual, "V2 encode map_large should match yjs")
    }

    @Test
    fun testEncodeV2TextLong() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_TEXT_LONG_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "A".repeat(1000))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_TEXT_LONG_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_long should match yjs")
    }

    @Test
    fun testEncodeV2TextUnicodeEmoji() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_EMOJI_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "Hello \uD83C\uDF0D\uD83C\uDF89 World")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_EMOJI_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_unicode_emoji should match yjs")
    }

    @Test
    fun testEncodeV2TextUnicodeCjk() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_CJK_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "\u4F60\u597D\u4E16\u754C\u3053\u3093\u306B\u3061\u306F")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_CJK_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_unicode_cjk should match yjs")
    }

    @Test
    fun testEncodeV2TextUnicodeArabic() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_ARABIC_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "\u0645\u0631\u062D\u0628\u0627 \u0628\u0627\u0644\u0639\u0627\u0644\u0645")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_TEXT_UNICODE_ARABIC_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_unicode_arabic should match yjs")
    }

    @Test
    fun testEncodeV2Nested3Levels() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_NESTED_3_LEVELS_CLIENT_ID
        val root = doc.getMap("root")
        val mid = YMap()
        root.set("mid", mid)
        val inner = YArray()
        mid.set("inner", inner)
        inner.push(listOf(1, 2, 3))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_NESTED_3_LEVELS_UPDATE_V2
        assertEquals(expected, actual, "V2 encode nested_3_levels should match yjs")
    }

    @Test
    fun testEncodeV2ArrayFloats() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_FLOATS_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf(1.5, -2.7, 0, 3.14159, -0.001))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_FLOATS_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_floats should match yjs")
    }

    @Test
    fun testEncodeV2ArrayLargeInts() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_LARGE_INTS_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf(0, -1, 2147483647, -2147483648, 1000000))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_LARGE_INTS_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_large_ints should match yjs")
    }

    @Test
    fun testEncodeV2MultiTypesSameDoc() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_MULTI_TYPES_SAME_DOC_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf(1, 2))
        val map = doc.getMap("map")
        map.set("key", "val")
        val text = doc.getText("text")
        text.insert(0, "hello")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_MULTI_TYPES_SAME_DOC_UPDATE_V2
        assertEquals(expected, actual, "V2 encode multi_types_same_doc should match yjs")
    }

    @Test
    fun testEncodeV2MapNestedTypes() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_MAP_NESTED_TYPES_CLIENT_ID
        val map = doc.getMap("map")
        val list = YArray()
        map.set("list", list)
        list.push(listOf("a", "b"))
        val nested = YMap()
        map.set("nested", nested)
        nested.set("x", 42)
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_MAP_NESTED_TYPES_UPDATE_V2
        assertEquals(expected, actual, "V2 encode map_nested_types should match yjs")
    }

    @Test
    fun testEncodeV2ArraySingleItem() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_SINGLE_ITEM_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf(42))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_SINGLE_ITEM_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_single_item should match yjs")
    }

    @Test
    fun testEncodeV2MapSingleEntry() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_MAP_SINGLE_ENTRY_CLIENT_ID
        val map = doc.getMap("map")
        map.set("only", "entry")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_MAP_SINGLE_ENTRY_UPDATE_V2
        assertEquals(expected, actual, "V2 encode map_single_entry should match yjs")
    }

    @Test
    fun testEncodeV2TextSingleChar() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_TEXT_SINGLE_CHAR_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "X")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_TEXT_SINGLE_CHAR_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_single_char should match yjs")
    }

    @Test
    fun testEncodeV2ArrayNestedArrays() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_NESTED_ARRAYS_CLIENT_ID
        val arr = doc.getArray("arr")
        val inner1 = YArray()
        val inner2 = YArray()
        arr.push(listOf(inner1, inner2))
        inner1.push(listOf(1, 2))
        inner2.push(listOf(3, 4))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_ARRAY_NESTED_ARRAYS_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_nested_arrays should match yjs")
    }

    @Test
    fun testEncodeV2MapBooleanNullValues() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_MAP_BOOLEAN_NULL_VALUES_CLIENT_ID
        val map = doc.getMap("map")
        map.set("t", true)
        map.set("f", false)
        map.set("n", null)
        map.set("zero", 0)
        map.set("empty", "")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_MAP_BOOLEAN_NULL_VALUES_UPDATE_V2
        assertEquals(expected, actual, "V2 encode map_boolean_null_values should match yjs")
    }

    @Test
    fun testEncodeV2TextMultiline() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.SINGLE_DOC_V2_TEXT_MULTILINE_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "line1\nline2\nline3")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.SINGLE_DOC_V2_TEXT_MULTILINE_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_multiline should match yjs")
    }

    // ==========================================================================
    // delete_ops_v2 — Encode Tests
    // ==========================================================================

    @Test
    fun testEncodeV2ArrayWithDelete() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_ARRAY_WITH_DELETE_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf("a", "b", "c", "d", "e"))
        arr.delete(1, 2) // delete 'b' and 'c'
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_ARRAY_WITH_DELETE_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_with_delete should match yjs")
    }

    @Test
    fun testEncodeV2MapWithDelete() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_MAP_WITH_DELETE_CLIENT_ID
        val map = doc.getMap("map")
        map.set("a", 1)
        map.set("b", 2)
        map.set("c", 3)
        map.delete("b")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_MAP_WITH_DELETE_UPDATE_V2
        assertEquals(expected, actual, "V2 encode map_with_delete should match yjs")
    }

    @Test
    fun testEncodeV2TextEditing() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_TEXT_EDITING_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "Hello")
        text.insert(5, " World")
        text.delete(5, 1) // delete the space
        text.insert(5, ", ")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_TEXT_EDITING_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_editing should match yjs")
    }

    @Test
    fun testEncodeV2MapOverwrite() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_MAP_OVERWRITE_CLIENT_ID
        val map = doc.getMap("map")
        map.set("key", "value1")
        map.set("key", "value2")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_MAP_OVERWRITE_UPDATE_V2
        assertEquals(expected, actual, "V2 encode map_overwrite should match yjs")
    }

    @Test
    fun testEncodeV2TextDeleteMiddle() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_MIDDLE_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "Hello World")
        text.delete(5, 1) // delete the space
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_MIDDLE_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_delete_middle should match yjs")
    }

    @Test
    fun testEncodeV2TextDeleteStart() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_START_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "Hello World")
        text.delete(0, 6) // delete "Hello "
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_START_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_delete_start should match yjs")
    }

    @Test
    fun testEncodeV2TextDeleteEnd() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_END_CLIENT_ID
        val text = doc.getText("text")
        text.insert(0, "Hello World")
        text.delete(5, 6) // delete " World"
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_TEXT_DELETE_END_UPDATE_V2
        assertEquals(expected, actual, "V2 encode text_delete_end should match yjs")
    }

    @Test
    fun testEncodeV2ArrayDeleteAll() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_ALL_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf(1, 2, 3, 4, 5))
        arr.delete(0, 5)
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_ALL_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_delete_all should match yjs")
    }

    @Test
    fun testEncodeV2ArrayDeleteThenReadd() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_THEN_READD_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf(1, 2, 3))
        arr.delete(0, 3)
        arr.push(listOf(4, 5, 6))
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_THEN_READD_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_delete_then_readd should match yjs")
    }

    @Test
    fun testEncodeV2MapOverwriteChain() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_MAP_OVERWRITE_CHAIN_CLIENT_ID
        val map = doc.getMap("map")
        map.set("key", "v1")
        map.set("key", "v2")
        map.set("key", "v3")
        map.set("key", "v4")
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_MAP_OVERWRITE_CHAIN_UPDATE_V2
        assertEquals(expected, actual, "V2 encode map_overwrite_chain should match yjs")
    }

    @Test
    fun testEncodeV2ArrayDeleteFirst() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_FIRST_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf("a", "b", "c"))
        arr.delete(0, 1)
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_FIRST_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_delete_first should match yjs")
    }

    @Test
    fun testEncodeV2ArrayDeleteLast() {
        val doc = Doc()
        doc.clientID = WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_LAST_CLIENT_ID
        val arr = doc.getArray("arr")
        arr.push(listOf("a", "b", "c"))
        arr.delete(2, 1)
        val encoded = encodeStateAsUpdateV2(doc)
        val actual = toHex(encoded)
        val expected = WireCompatFixtures.DELETE_OPS_V2_ARRAY_DELETE_LAST_UPDATE_V2
        assertEquals(expected, actual, "V2 encode array_delete_last should match yjs")
    }

    // ==========================================================================
    // Cross-format round-trip: decode V2 then re-encode V2 should yield same bytes
    // ==========================================================================

    @Test
    fun testRoundTripV2ArrayInts() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_INTS_UPDATE_V2)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_INTS_UPDATE_V2, reencoded,
            "V2 round-trip array_ints: decode then re-encode should match")
    }

    @Test
    fun testRoundTripV2MapStrings() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MAP_STRINGS_UPDATE_V2)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_MAP_STRINGS_UPDATE_V2, reencoded,
            "V2 round-trip map_strings: decode then re-encode should match")
    }

    @Test
    fun testRoundTripV2TextSimple() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_SIMPLE_UPDATE_V2)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_TEXT_SIMPLE_UPDATE_V2, reencoded,
            "V2 round-trip text_simple: decode then re-encode should match")
    }

    @Test
    fun testRoundTripV2EmptyDoc() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_EMPTY_DOC_UPDATE_V2)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_EMPTY_DOC_UPDATE_V2, reencoded,
            "V2 round-trip empty_doc: decode then re-encode should match")
    }

    @Test
    fun testRoundTripV2ArrayMixedTypes() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_MIXED_TYPES_UPDATE_V2)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_MIXED_TYPES_UPDATE_V2, reencoded,
            "V2 round-trip array_mixed_types: decode then re-encode should match")
    }

    @Test
    fun testRoundTripV2NestedMapArray() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_NESTED_MAP_ARRAY_UPDATE_V2)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_NESTED_MAP_ARRAY_UPDATE_V2, reencoded,
            "V2 round-trip nested_map_array: decode then re-encode should match")
    }

    @Test
    fun testRoundTripV2MultiTypesSameDoc() {
        val doc = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MULTI_TYPES_SAME_DOC_UPDATE_V2)
        val reencoded = toHex(encodeStateAsUpdateV2(doc))
        assertEquals(WireCompatFixtures.SINGLE_DOC_V2_MULTI_TYPES_SAME_DOC_UPDATE_V2, reencoded,
            "V2 round-trip multi_types_same_doc: decode then re-encode should match")
    }

    // ==========================================================================
    // V2 decode then V1 encode cross-check: state equivalence
    // ==========================================================================

    @Test
    fun testV2DecodeProducesEquivalentStateToV1() {
        // Decode both V1 and V2 array_ints, verify they produce the same state
        val docV1 = Doc()
        applyUpdate(docV1, hexToBytes(WireCompatFixtures.SINGLE_DOC_V1_ARRAY_INTS_UPDATE))
        val docV2 = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_ARRAY_INTS_UPDATE_V2)

        val arrV1 = docV1.getArray("arr")
        val arrV2 = docV2.getArray("arr")
        assertEquals(arrV1.toArray(), arrV2.toArray(),
            "V1 and V2 decode of array_ints should produce same state")
    }

    @Test
    fun testV2DecodeMapEquivalentToV1() {
        val docV1 = Doc()
        applyUpdate(docV1, hexToBytes(WireCompatFixtures.SINGLE_DOC_V1_MAP_STRINGS_UPDATE))
        val docV2 = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_MAP_STRINGS_UPDATE_V2)

        val mapV1 = docV1.getMap("map")
        val mapV2 = docV2.getMap("map")
        assertEquals(mapV1.get("key1"), mapV2.get("key1"))
        assertEquals(mapV1.get("key2"), mapV2.get("key2"))
    }

    @Test
    fun testV2DecodeTextEquivalentToV1() {
        val docV1 = Doc()
        applyUpdate(docV1, hexToBytes(WireCompatFixtures.SINGLE_DOC_V1_TEXT_SIMPLE_UPDATE))
        val docV2 = applyFixtureV2(WireCompatFixtures.SINGLE_DOC_V2_TEXT_SIMPLE_UPDATE_V2)

        assertEquals(docV1.getText("text").toString(), docV2.getText("text").toString(),
            "V1 and V2 decode of text_simple should produce same state")
    }
}
