package yks

import yks.utils.*
import yks.types.*
import kotlin.test.*

/**
 * Bidirectional sync wire-compatibility tests against binary fixtures generated by JavaScript yjs.
 *
 * Every test reproduces the exact same operations as the yjs fixture generator (fixtures/generate.mjs),
 * then verifies all intermediate bytes and final states match the yjs output.
 *
 * Byte-exact verification is used for:
 * - Pre-sync state vectors (single-client, deterministic)
 * - Incremental updates (single-source client, deterministic encoding order)
 *
 * Semantic equivalence verification is used for:
 * - Merged updates and merged state vectors after sync (client ordering in the encoding
 *   is non-deterministic across implementations due to HashMap iteration order)
 *
 * Additionally, yjs-generated merged updates are applied to fresh docs to verify
 * cross-implementation decode compatibility, and decoded state vectors are checked
 * for correct client->clock values.
 *
 * Fixtures generated by yjs 13.6.30.
 */
class WireCompatSyncTest {

    // ── Helpers ──

    private fun hexToBytes(hex: String): ByteArray {
        val result = ByteArray(hex.length / 2)
        for (i in result.indices) {
            result[i] = hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return result
    }

    private fun toHex(bytes: ByteArray): String {
        return bytes.joinToString("") {
            val v = it.toInt() and 0xFF
            val hi = v shr 4
            val lo = v and 0x0F
            "${HEX_CHARS[hi]}${HEX_CHARS[lo]}"
        }
    }

    companion object {
        private const val HEX_CHARS = "0123456789abcdef"
    }

    private fun newDoc(clientID: Int): Doc {
        val doc = Doc()
        doc.clientID = clientID
        return doc
    }

    /**
     * Assert two state vectors are semantically equal (same client->clock entries).
     * Client ordering in the binary encoding is non-deterministic (depends on HashMap
     * iteration order), so we compare decoded maps rather than raw bytes.
     */
    private fun assertStateVectorEquals(expectedHex: String, actualBytes: ByteArray, message: String) {
        val expected = decodeStateVector(hexToBytes(expectedHex))
        val actual = decodeStateVector(actualBytes)
        assertEquals(expected, actual, message)
    }

    /**
     * Assert two encoded updates produce the same document state when applied to a fresh doc.
     * Update encoding order of clients is non-deterministic after sync (depends on HashMap
     * iteration order), so we compare the resulting document states rather than raw bytes.
     */
    private fun assertUpdateEquivalent(expectedHex: String, actualBytes: ByteArray, message: String) {
        val docExpected = Doc()
        applyUpdate(docExpected, hexToBytes(expectedHex))
        val docActual = Doc()
        applyUpdate(docActual, actualBytes)
        assertEquals(docExpected.toJSON(), docActual.toJSON(), message)
        // Also verify they produce the same state vector (semantically)
        val svExpected = decodeStateVector(encodeStateVector(docExpected))
        val svActual = decodeStateVector(encodeStateVector(docActual))
        assertEquals(svExpected, svActual, "$message (state vectors differ)")
    }

    // ── two_client_array_concurrent ──
    // doc1 (clientID=100): arr.push(["a", "b"])
    // doc2 (clientID=200): arr.push(["c", "d"])

    @Test
    fun testSyncV1TwoClientArrayConcurrent_stateVectorsBeforeSync() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_B)

        doc1.getArray("arr").push(listOf("a", "b"))
        doc2.getArray("arr").push(listOf("c", "d"))

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_SV1BEFORE,
            toHex(sv1),
            "sv1Before mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_SV2BEFORE,
            toHex(sv2),
            "sv2Before mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientArrayConcurrent_incrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_B)

        doc1.getArray("arr").push(listOf("a", "b"))
        doc2.getArray("arr").push(listOf("c", "d"))

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        val update1to2 = encodeStateAsUpdate(doc1, sv2)
        val update2to1 = encodeStateAsUpdate(doc2, sv1)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_UPDATE1TO2,
            toHex(update1to2),
            "update1to2 mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_UPDATE2TO1,
            toHex(update2to1),
            "update2to1 mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientArrayConcurrent_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_B)

        doc1.getArray("arr").push(listOf("a", "b"))
        doc2.getArray("arr").push(listOf("c", "d"))

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        val update1to2 = encodeStateAsUpdate(doc1, sv2)
        val update2to1 = encodeStateAsUpdate(doc2, sv1)

        applyUpdate(doc2, update1to2)
        applyUpdate(doc1, update2to1)

        // Both docs must converge
        val arr1 = doc1.getArray("arr").toArray()
        val arr2 = doc2.getArray("arr").toArray()
        assertEquals(arr1, arr2, "docs did not converge")

        // Verify expected state
        assertEquals(listOf("a", "b", "c", "d"), arr1, "expected state mismatch")

        // Verify merged update (semantic equivalence — client ordering in encoding is non-deterministic)
        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )

        // Verify merged state vector (semantic equivalence)
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    // ── two_client_map_different_keys ──
    // doc1 (clientID=101): map.set("x", 1)
    // doc2 (clientID=201): map.set("y", 2)

    @Test
    fun testSyncV1TwoClientMapDifferentKeys_stateVectorsBeforeSync() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_CLIENT_B)

        doc1.getMap("map").set("x", 1)
        doc2.getMap("map").set("y", 2)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_SV1BEFORE,
            toHex(encodeStateVector(doc1)),
            "sv1Before mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_SV2BEFORE,
            toHex(encodeStateVector(doc2)),
            "sv2Before mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientMapDifferentKeys_incrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_CLIENT_B)

        doc1.getMap("map").set("x", 1)
        doc2.getMap("map").set("y", 2)

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        val update1to2 = encodeStateAsUpdate(doc1, sv2)
        val update2to1 = encodeStateAsUpdate(doc2, sv1)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_UPDATE1TO2,
            toHex(update1to2),
            "update1to2 mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_UPDATE2TO1,
            toHex(update2to1),
            "update2to1 mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientMapDifferentKeys_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_CLIENT_B)

        doc1.getMap("map").set("x", 1)
        doc2.getMap("map").set("y", 2)

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
        applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))

        // Convergence
        val map1 = doc1.getMap("map")
        val map2 = doc2.getMap("map")
        assertEquals(1, map1.get("x"))
        assertEquals(2, map1.get("y"))
        assertEquals(1, map2.get("x"))
        assertEquals(2, map2.get("y"))

        // Merged update (semantic equivalence)
        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )

        // Merged state vector (semantic equivalence)
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    // ── two_client_map_same_key ──
    // doc1 (clientID=102): map.set("key", "from-A")
    // doc2 (clientID=202): map.set("key", "from-B")

    @Test
    fun testSyncV1TwoClientMapSameKey_stateVectorsBeforeSync() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_B)

        doc1.getMap("map").set("key", "from-A")
        doc2.getMap("map").set("key", "from-B")

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_SV1BEFORE,
            toHex(encodeStateVector(doc1)),
            "sv1Before mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_SV2BEFORE,
            toHex(encodeStateVector(doc2)),
            "sv2Before mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientMapSameKey_incrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_B)

        doc1.getMap("map").set("key", "from-A")
        doc2.getMap("map").set("key", "from-B")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_UPDATE1TO2,
            toHex(encodeStateAsUpdate(doc1, sv2)),
            "update1to2 mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_UPDATE2TO1,
            toHex(encodeStateAsUpdate(doc2, sv1)),
            "update2to1 mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientMapSameKey_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_B)

        doc1.getMap("map").set("key", "from-A")
        doc2.getMap("map").set("key", "from-B")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
        applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))

        // In yjs, higher clientID wins for same-key conflicts: clientB=202 > clientA=102
        val map1 = doc1.getMap("map")
        val map2 = doc2.getMap("map")
        assertEquals("from-B", map1.get("key"), "doc1 should see from-B (higher clientID wins)")
        assertEquals("from-B", map2.get("key"), "doc2 should see from-B (higher clientID wins)")
        assertEquals(map1.get("key"), map2.get("key"), "docs did not converge")

        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    // ── two_client_text_same_position ──
    // doc1 (clientID=103): text.insert(0, "AAA")
    // doc2 (clientID=203): text.insert(0, "BBB")

    @Test
    fun testSyncV1TwoClientTextSamePosition_stateVectorsBeforeSync() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_B)

        doc1.getText("text").insert(0, "AAA")
        doc2.getText("text").insert(0, "BBB")

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_SV1BEFORE,
            toHex(encodeStateVector(doc1)),
            "sv1Before mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_SV2BEFORE,
            toHex(encodeStateVector(doc2)),
            "sv2Before mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientTextSamePosition_incrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_B)

        doc1.getText("text").insert(0, "AAA")
        doc2.getText("text").insert(0, "BBB")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_UPDATE1TO2,
            toHex(encodeStateAsUpdate(doc1, sv2)),
            "update1to2 mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_UPDATE2TO1,
            toHex(encodeStateAsUpdate(doc2, sv1)),
            "update2to1 mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientTextSamePosition_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_B)

        doc1.getText("text").insert(0, "AAA")
        doc2.getText("text").insert(0, "BBB")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
        applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))

        val text1 = doc1.getText("text").toString()
        val text2 = doc2.getText("text").toString()
        assertEquals(text1, text2, "docs did not converge")
        // yjs expected: "AAABBB" — lower clientID (103) content comes first
        assertEquals("AAABBB", text1, "expected text mismatch")

        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    // ── two_client_mixed_types ──
    // doc1 (clientID=104): arr.push([1, 2]), map.set("a", "from-A")
    // doc2 (clientID=204): arr.push([3, 4]), map.set("b", "from-B")

    @Test
    fun testSyncV1TwoClientMixedTypes_stateVectorsBeforeSync() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_CLIENT_B)

        doc1.getArray("arr").push(listOf(1, 2))
        doc1.getMap("map").set("a", "from-A")
        doc2.getArray("arr").push(listOf(3, 4))
        doc2.getMap("map").set("b", "from-B")

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_SV1BEFORE,
            toHex(encodeStateVector(doc1)),
            "sv1Before mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_SV2BEFORE,
            toHex(encodeStateVector(doc2)),
            "sv2Before mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientMixedTypes_incrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_CLIENT_B)

        doc1.getArray("arr").push(listOf(1, 2))
        doc1.getMap("map").set("a", "from-A")
        doc2.getArray("arr").push(listOf(3, 4))
        doc2.getMap("map").set("b", "from-B")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_UPDATE1TO2,
            toHex(encodeStateAsUpdate(doc1, sv2)),
            "update1to2 mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_UPDATE2TO1,
            toHex(encodeStateAsUpdate(doc2, sv1)),
            "update2to1 mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientMixedTypes_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_CLIENT_B)

        doc1.getArray("arr").push(listOf(1, 2))
        doc1.getMap("map").set("a", "from-A")
        doc2.getArray("arr").push(listOf(3, 4))
        doc2.getMap("map").set("b", "from-B")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
        applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))

        // Verify convergence
        val arr1 = doc1.getArray("arr").toArray()
        val arr2 = doc2.getArray("arr").toArray()
        assertEquals(arr1, arr2, "arrays did not converge")
        assertEquals(listOf(1, 2, 3, 4), arr1, "expected array mismatch")

        val map1 = doc1.getMap("map")
        val map2 = doc2.getMap("map")
        assertEquals("from-A", map1.get("a"))
        assertEquals("from-B", map1.get("b"))
        assertEquals("from-A", map2.get("a"))
        assertEquals("from-B", map2.get("b"))

        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    // ── two_client_array_interleave ──
    // doc1 (clientID=105): arr.push(["a1", "a2", "a3"])
    // doc2 (clientID=205): arr.push(["b1", "b2", "b3"])

    @Test
    fun testSyncV1TwoClientArrayInterleave_stateVectorsBeforeSync() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_CLIENT_B)

        doc1.getArray("arr").push(listOf("a1", "a2", "a3"))
        doc2.getArray("arr").push(listOf("b1", "b2", "b3"))

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_SV1BEFORE,
            toHex(encodeStateVector(doc1)),
            "sv1Before mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_SV2BEFORE,
            toHex(encodeStateVector(doc2)),
            "sv2Before mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientArrayInterleave_incrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_CLIENT_B)

        doc1.getArray("arr").push(listOf("a1", "a2", "a3"))
        doc2.getArray("arr").push(listOf("b1", "b2", "b3"))

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_UPDATE1TO2,
            toHex(encodeStateAsUpdate(doc1, sv2)),
            "update1to2 mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_UPDATE2TO1,
            toHex(encodeStateAsUpdate(doc2, sv1)),
            "update2to1 mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientArrayInterleave_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_CLIENT_B)

        doc1.getArray("arr").push(listOf("a1", "a2", "a3"))
        doc2.getArray("arr").push(listOf("b1", "b2", "b3"))

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
        applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))

        val arr1 = doc1.getArray("arr").toArray()
        val arr2 = doc2.getArray("arr").toArray()
        assertEquals(arr1, arr2, "docs did not converge")
        assertEquals(listOf("a1", "a2", "a3", "b1", "b2", "b3"), arr1, "expected array mismatch")

        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    // ── two_client_text_different_positions ──
    // doc1 (clientID=106): text.insert(0, "Hello")
    // doc2 (clientID=206): text.insert(0, "World")

    @Test
    fun testSyncV1TwoClientTextDifferentPositions_stateVectorsBeforeSync() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_CLIENT_B)

        doc1.getText("text").insert(0, "Hello")
        doc2.getText("text").insert(0, "World")

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_SV1BEFORE,
            toHex(encodeStateVector(doc1)),
            "sv1Before mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_SV2BEFORE,
            toHex(encodeStateVector(doc2)),
            "sv2Before mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientTextDifferentPositions_incrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_CLIENT_B)

        doc1.getText("text").insert(0, "Hello")
        doc2.getText("text").insert(0, "World")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_UPDATE1TO2,
            toHex(encodeStateAsUpdate(doc1, sv2)),
            "update1to2 mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_UPDATE2TO1,
            toHex(encodeStateAsUpdate(doc2, sv1)),
            "update2to1 mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientTextDifferentPositions_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_CLIENT_B)

        doc1.getText("text").insert(0, "Hello")
        doc2.getText("text").insert(0, "World")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
        applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))

        val text1 = doc1.getText("text").toString()
        val text2 = doc2.getText("text").toString()
        assertEquals(text1, text2, "docs did not converge")
        assertEquals("HelloWorld", text1, "expected text mismatch")

        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    // ── two_client_map_overwrite_conflict ──
    // doc1 (clientID=107): map.set("shared", "A-first"), map.set("shared", "A-second")
    // doc2 (clientID=207): map.set("shared", "B-first"), map.set("shared", "B-second")

    @Test
    fun testSyncV1TwoClientMapOverwriteConflict_stateVectorsBeforeSync() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_B)

        val map1 = doc1.getMap("map")
        map1.set("shared", "A-first")
        map1.set("shared", "A-second")

        val map2 = doc2.getMap("map")
        map2.set("shared", "B-first")
        map2.set("shared", "B-second")

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_SV1BEFORE,
            toHex(encodeStateVector(doc1)),
            "sv1Before mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_SV2BEFORE,
            toHex(encodeStateVector(doc2)),
            "sv2Before mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientMapOverwriteConflict_incrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_B)

        val map1 = doc1.getMap("map")
        map1.set("shared", "A-first")
        map1.set("shared", "A-second")

        val map2 = doc2.getMap("map")
        map2.set("shared", "B-first")
        map2.set("shared", "B-second")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)

        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_UPDATE1TO2,
            toHex(encodeStateAsUpdate(doc1, sv2)),
            "update1to2 mismatch"
        )
        assertEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_UPDATE2TO1,
            toHex(encodeStateAsUpdate(doc2, sv1)),
            "update2to1 mismatch"
        )
    }

    @Test
    fun testSyncV1TwoClientMapOverwriteConflict_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_B)

        val map1 = doc1.getMap("map")
        map1.set("shared", "A-first")
        map1.set("shared", "A-second")

        val map2 = doc2.getMap("map")
        map2.set("shared", "B-first")
        map2.set("shared", "B-second")

        val sv1 = encodeStateVector(doc1)
        val sv2 = encodeStateVector(doc2)
        applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
        applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))

        // Higher clientID (207) wins: "B-second"
        assertEquals("B-second", doc1.getMap("map").get("shared"), "doc1 should see B-second")
        assertEquals("B-second", doc2.getMap("map").get("shared"), "doc2 should see B-second")

        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    // ── three_client_chain ──
    // doc1 (clientID=110): m.set("a", 1)
    // doc2 (clientID=120): m.set("b", 2)
    // doc3 (clientID=130): m.set("c", 3)
    // Sync chain: 1<->2, 2<->3, 1<->3

    @Test
    fun testSyncV1ThreeClientChain_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_B)
        val doc3 = newDoc(WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_C)

        doc1.getMap("m").set("a", 1)
        doc2.getMap("m").set("b", 2)
        doc3.getMap("m").set("c", 3)

        // Sync 1 <-> 2
        run {
            val sv1 = encodeStateVector(doc1)
            val sv2 = encodeStateVector(doc2)
            applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
            applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))
        }

        // Sync 2 <-> 3
        run {
            val sv2 = encodeStateVector(doc2)
            val sv3 = encodeStateVector(doc3)
            applyUpdate(doc3, encodeStateAsUpdate(doc2, sv3))
            applyUpdate(doc2, encodeStateAsUpdate(doc3, sv2))
        }

        // Sync 1 <-> 3 (to fully converge)
        run {
            val sv1 = encodeStateVector(doc1)
            val sv3 = encodeStateVector(doc3)
            applyUpdate(doc3, encodeStateAsUpdate(doc1, sv3))
            applyUpdate(doc1, encodeStateAsUpdate(doc3, sv1))
        }

        // All three docs must converge
        val m1 = doc1.getMap("m")
        val m2 = doc2.getMap("m")
        val m3 = doc3.getMap("m")

        assertEquals(1, m1.get("a"))
        assertEquals(2, m1.get("b"))
        assertEquals(3, m1.get("c"))
        assertEquals(m1.entries(), m2.entries(), "doc1 and doc2 did not converge")
        assertEquals(m2.entries(), m3.entries(), "doc2 and doc3 did not converge")

        // Verify merged update from doc1 (semantic equivalence)
        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    @Test
    fun testSyncV1ThreeClientChain_allDocsProduceSameMergedUpdate() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_B)
        val doc3 = newDoc(WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_C)

        doc1.getMap("m").set("a", 1)
        doc2.getMap("m").set("b", 2)
        doc3.getMap("m").set("c", 3)

        // Full sync chain
        run {
            val sv1 = encodeStateVector(doc1)
            val sv2 = encodeStateVector(doc2)
            applyUpdate(doc2, encodeStateAsUpdate(doc1, sv2))
            applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1))
        }
        run {
            val sv2 = encodeStateVector(doc2)
            val sv3 = encodeStateVector(doc3)
            applyUpdate(doc3, encodeStateAsUpdate(doc2, sv3))
            applyUpdate(doc2, encodeStateAsUpdate(doc3, sv2))
        }
        run {
            val sv1 = encodeStateVector(doc1)
            val sv3 = encodeStateVector(doc3)
            applyUpdate(doc3, encodeStateAsUpdate(doc1, sv3))
            applyUpdate(doc1, encodeStateAsUpdate(doc3, sv1))
        }

        // All three docs should produce semantically identical merged updates and state vectors
        // (byte ordering of clients may differ due to HashMap iteration order)
        assertUpdateEquivalent(
            toHex(encodeStateAsUpdate(doc1)),
            encodeStateAsUpdate(doc2),
            "doc1 and doc2 produce different merged updates"
        )
        assertUpdateEquivalent(
            toHex(encodeStateAsUpdate(doc2)),
            encodeStateAsUpdate(doc3),
            "doc2 and doc3 produce different merged updates"
        )

        assertStateVectorEquals(
            toHex(encodeStateVector(doc1)),
            encodeStateVector(doc2),
            "doc1 and doc2 produce different state vectors"
        )
        assertStateVectorEquals(
            toHex(encodeStateVector(doc2)),
            encodeStateVector(doc3),
            "doc2 and doc3 produce different state vectors"
        )
    }

    // ── incremental_two_rounds ──
    // Round 1: doc1 (clientID=140) pushes [1,2], syncs to doc2 (clientID=150)
    // Round 2: doc2 pushes [3,4], syncs back to doc1

    @Test
    fun testSyncV1IncrementalTwoRounds_round1StateVectorAndUpdate() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_B)

        // Round 1: doc1 creates data
        doc1.getArray("arr").push(listOf(1, 2))

        // Verify doc2's state vector before sync (empty)
        val sv2r1 = encodeStateVector(doc2)
        assertEquals(
            WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_SV2ROUND1,
            toHex(sv2r1),
            "sv2Round1 mismatch"
        )

        // Verify update1to2 for round 1
        val u1to2r1 = encodeStateAsUpdate(doc1, sv2r1)
        assertEquals(
            WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_UPDATE1TO2ROUND1,
            toHex(u1to2r1),
            "update1to2Round1 mismatch"
        )
    }

    @Test
    fun testSyncV1IncrementalTwoRounds_round2StateVectorAndUpdate() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_B)

        // Round 1: doc1 creates data, syncs to doc2
        doc1.getArray("arr").push(listOf(1, 2))
        val sv2r1 = encodeStateVector(doc2)
        val u1to2r1 = encodeStateAsUpdate(doc1, sv2r1)
        applyUpdate(doc2, u1to2r1)

        // Round 2: doc2 pushes more data
        doc2.getArray("arr").push(listOf(3, 4))

        // Verify doc1's state vector before round 2 sync
        val sv1r2 = encodeStateVector(doc1)
        assertEquals(
            WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_SV1ROUND2,
            toHex(sv1r2),
            "sv1Round2 mismatch"
        )

        // Verify incremental update2to1 for round 2
        val u2to1r2 = encodeStateAsUpdate(doc2, sv1r2)
        assertEquals(
            WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_UPDATE2TO1ROUND2,
            toHex(u2to1r2),
            "update2to1Round2 mismatch"
        )
    }

    @Test
    fun testSyncV1IncrementalTwoRounds_convergenceAndMergedState() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_B)

        // Round 1: doc1 creates data, syncs to doc2
        doc1.getArray("arr").push(listOf(1, 2))
        val sv2r1 = encodeStateVector(doc2)
        val u1to2r1 = encodeStateAsUpdate(doc1, sv2r1)
        applyUpdate(doc2, u1to2r1)

        // Round 2: doc2 pushes more data, syncs back
        doc2.getArray("arr").push(listOf(3, 4))
        val sv1r2 = encodeStateVector(doc1)
        val u2to1r2 = encodeStateAsUpdate(doc2, sv1r2)
        applyUpdate(doc1, u2to1r2)

        // Verify convergence
        val arr1 = doc1.getArray("arr").toArray()
        val arr2 = doc2.getArray("arr").toArray()
        assertEquals(arr1, arr2, "docs did not converge")
        assertEquals(listOf(1, 2, 3, 4), arr1, "expected array mismatch")

        // Verify merged update (semantic equivalence)
        assertUpdateEquivalent(
            WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "mergedUpdate mismatch"
        )

        // Verify merged state vector (semantic equivalence)
        assertStateVectorEquals(
            WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "mergedStateVector mismatch"
        )
    }

    @Test
    fun testSyncV1IncrementalTwoRounds_allIntermediateBytes() {
        // End-to-end test verifying every single intermediate byte across both rounds
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_B)

        // Round 1
        doc1.getArray("arr").push(listOf(1, 2))

        val sv2r1 = encodeStateVector(doc2)
        assertEquals(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_SV2ROUND1, toHex(sv2r1),
            "Round 1: sv2 mismatch")

        val u1to2r1 = encodeStateAsUpdate(doc1, sv2r1)
        assertEquals(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_UPDATE1TO2ROUND1, toHex(u1to2r1),
            "Round 1: update1to2 mismatch")

        applyUpdate(doc2, u1to2r1)

        // Round 2
        doc2.getArray("arr").push(listOf(3, 4))

        val sv1r2 = encodeStateVector(doc1)
        assertEquals(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_SV1ROUND2, toHex(sv1r2),
            "Round 2: sv1 mismatch")

        val u2to1r2 = encodeStateAsUpdate(doc2, sv1r2)
        assertEquals(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_UPDATE2TO1ROUND2, toHex(u2to1r2),
            "Round 2: update2to1 mismatch")

        applyUpdate(doc1, u2to1r2)

        // Final merged state (semantic equivalence)
        assertUpdateEquivalent(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_MERGED_UPDATE,
            encodeStateAsUpdate(doc1),
            "Final: mergedUpdate mismatch")
        assertStateVectorEquals(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_MERGED_STATE_VECTOR,
            encodeStateVector(doc1),
            "Final: mergedStateVector mismatch")

        // Both docs must produce semantically identical merged output
        assertUpdateEquivalent(toHex(encodeStateAsUpdate(doc1)), encodeStateAsUpdate(doc2),
            "doc1 and doc2 produce different merged updates after full sync")
    }

    // ── Cross-apply verification: apply yjs-generated merged update to fresh doc ──

    @Test
    fun testSyncV1ArrayConcurrent_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_MERGED_UPDATE))
        val arr = doc.getArray("arr")
        assertEquals(4, arr.length)
        assertEquals(setOf("a", "b", "c", "d"), arr.toArray().toSet())
    }

    @Test
    fun testSyncV1MapDifferentKeys_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_MERGED_UPDATE))
        val map = doc.getMap("map")
        assertEquals(1, map.get("x"))
        assertEquals(2, map.get("y"))
    }

    @Test
    fun testSyncV1MapSameKey_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_MERGED_UPDATE))
        val map = doc.getMap("map")
        assertEquals("from-B", map.get("key"))
    }

    @Test
    fun testSyncV1TextSamePosition_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_MERGED_UPDATE))
        val text = doc.getText("text")
        assertEquals("AAABBB", text.toString())
    }

    @Test
    fun testSyncV1MixedTypes_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_MERGED_UPDATE))
        val arr = doc.getArray("arr")
        assertEquals(listOf(1, 2, 3, 4), arr.toArray())
        val map = doc.getMap("map")
        assertEquals("from-A", map.get("a"))
        assertEquals("from-B", map.get("b"))
    }

    @Test
    fun testSyncV1ArrayInterleave_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_MERGED_UPDATE))
        val arr = doc.getArray("arr")
        assertEquals(6, arr.length)
        assertEquals(listOf("a1", "a2", "a3", "b1", "b2", "b3"), arr.toArray())
    }

    @Test
    fun testSyncV1TextDifferentPositions_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_MERGED_UPDATE))
        val text = doc.getText("text")
        assertEquals("HelloWorld", text.toString())
    }

    @Test
    fun testSyncV1MapOverwriteConflict_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_MERGED_UPDATE))
        val map = doc.getMap("map")
        assertEquals("B-second", map.get("shared"))
    }

    @Test
    fun testSyncV1ThreeClientChain_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_MERGED_UPDATE))
        val m = doc.getMap("m")
        assertEquals(1, m.get("a"))
        assertEquals(2, m.get("b"))
        assertEquals(3, m.get("c"))
    }

    @Test
    fun testSyncV1IncrementalTwoRounds_applyYjsMergedUpdate() {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_MERGED_UPDATE))
        val arr = doc.getArray("arr")
        assertEquals(listOf(1, 2, 3, 4), arr.toArray())
    }

    // ── State vector decode verification ──

    @Test
    fun testSyncV1ArrayConcurrent_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_MERGED_STATE_VECTOR))
        assertEquals(2, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_A])
        assertEquals(2, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_B])
    }

    @Test
    fun testSyncV1MapDifferentKeys_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_MERGED_STATE_VECTOR))
        assertEquals(1, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_CLIENT_A])
        assertEquals(1, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_DIFFERENT_KEYS_CLIENT_B])
    }

    @Test
    fun testSyncV1MapSameKey_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_MERGED_STATE_VECTOR))
        assertEquals(1, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_A])
        assertEquals(1, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_B])
    }

    @Test
    fun testSyncV1TextSamePosition_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_MERGED_STATE_VECTOR))
        assertEquals(3, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_A])
        assertEquals(3, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_B])
    }

    @Test
    fun testSyncV1MixedTypes_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_MERGED_STATE_VECTOR))
        assertEquals(3, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_CLIENT_A])
        assertEquals(3, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_MIXED_TYPES_CLIENT_B])
    }

    @Test
    fun testSyncV1ArrayInterleave_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_MERGED_STATE_VECTOR))
        assertEquals(3, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_CLIENT_A])
        assertEquals(3, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_INTERLEAVE_CLIENT_B])
    }

    @Test
    fun testSyncV1TextDifferentPositions_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_MERGED_STATE_VECTOR))
        assertEquals(5, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_CLIENT_A])
        assertEquals(5, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_DIFFERENT_POSITIONS_CLIENT_B])
    }

    @Test
    fun testSyncV1MapOverwriteConflict_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_MERGED_STATE_VECTOR))
        assertEquals(2, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_A])
        assertEquals(2, sv[WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_B])
    }

    @Test
    fun testSyncV1ThreeClientChain_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_MERGED_STATE_VECTOR))
        assertEquals(1, sv[WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_A])
        assertEquals(1, sv[WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_B])
        assertEquals(1, sv[WireCompatFixtures.SYNC_V1_THREE_CLIENT_CHAIN_CLIENT_C])
    }

    @Test
    fun testSyncV1IncrementalTwoRounds_decodeMergedStateVector() {
        val sv = decodeStateVector(hexToBytes(WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_MERGED_STATE_VECTOR))
        assertEquals(2, sv[WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_A])
        assertEquals(2, sv[WireCompatFixtures.SYNC_V1_INCREMENTAL_TWO_ROUNDS_CLIENT_B])
    }

    // ── Bidirectional cross-apply: apply yjs incremental updates to yks docs ──

    @Test
    fun testSyncV1ArrayConcurrent_applyYjsIncrementalUpdates() {
        // Create docs with same operations as yjs, then apply yjs-generated incremental updates
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_CLIENT_B)

        doc1.getArray("arr").push(listOf("a", "b"))
        doc2.getArray("arr").push(listOf("c", "d"))

        // Apply yjs-generated incremental updates (the exact bytes from yjs)
        applyUpdate(doc2, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_UPDATE1TO2))
        applyUpdate(doc1, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_ARRAY_CONCURRENT_UPDATE2TO1))

        assertEquals(listOf("a", "b", "c", "d"), doc1.getArray("arr").toArray())
        assertEquals(listOf("a", "b", "c", "d"), doc2.getArray("arr").toArray())
    }

    @Test
    fun testSyncV1MapSameKey_applyYjsIncrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_CLIENT_B)

        doc1.getMap("map").set("key", "from-A")
        doc2.getMap("map").set("key", "from-B")

        applyUpdate(doc2, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_UPDATE1TO2))
        applyUpdate(doc1, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_SAME_KEY_UPDATE2TO1))

        assertEquals("from-B", doc1.getMap("map").get("key"))
        assertEquals("from-B", doc2.getMap("map").get("key"))
    }

    @Test
    fun testSyncV1TextSamePosition_applyYjsIncrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_CLIENT_B)

        doc1.getText("text").insert(0, "AAA")
        doc2.getText("text").insert(0, "BBB")

        applyUpdate(doc2, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_UPDATE1TO2))
        applyUpdate(doc1, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_TEXT_SAME_POSITION_UPDATE2TO1))

        assertEquals("AAABBB", doc1.getText("text").toString())
        assertEquals("AAABBB", doc2.getText("text").toString())
    }

    @Test
    fun testSyncV1MapOverwriteConflict_applyYjsIncrementalUpdates() {
        val doc1 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_A)
        val doc2 = newDoc(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_CLIENT_B)

        val map1 = doc1.getMap("map")
        map1.set("shared", "A-first")
        map1.set("shared", "A-second")

        val map2 = doc2.getMap("map")
        map2.set("shared", "B-first")
        map2.set("shared", "B-second")

        applyUpdate(doc2, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_UPDATE1TO2))
        applyUpdate(doc1, hexToBytes(WireCompatFixtures.SYNC_V1_TWO_CLIENT_MAP_OVERWRITE_CONFLICT_UPDATE2TO1))

        assertEquals("B-second", doc1.getMap("map").get("shared"))
        assertEquals("B-second", doc2.getMap("map").get("shared"))
    }
}
