package yks

import yks.utils.*
import kotlin.test.*

/**
 * Wire compatibility tests for GC-origin resolution.
 *
 * These verify that yks handles the case where a remote update's origin or
 * rightOrigin points to a garbage-collected struct — matching Yjs behavior.
 * GC structs arise when a parent item is deleted, causing its children to be GC'd.
 * Fixtures generated by Yjs 13.6.30.
 */
class WireCompatGCOriginTest {

    private fun hexToBytes(hex: String): ByteArray {
        val result = ByteArray(hex.length / 2)
        for (i in result.indices) {
            result[i] = hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return result
    }

    private fun applyGCOriginFixture(fullUpdateAHex: String, updateBpendingHex: String): Doc {
        val doc = Doc()
        applyUpdate(doc, hexToBytes(fullUpdateAHex))
        applyUpdate(doc, hexToBytes(updateBpendingHex))
        return doc
    }

    @Test
    fun testNestedArrayOriginGC() {
        val doc = applyGCOriginFixture(
            WireCompatFixtures.GC_ORIGIN_NESTED_ARRAY_ORIGIN_GC_FULL_UPDATE_A,
            WireCompatFixtures.GC_ORIGIN_NESTED_ARRAY_ORIGIN_GC_UPDATE_BPENDING
        )
        val arr = doc.getArray("arr")
        assertEquals(0, arr.length)
    }

    @Test
    fun testNestedTextOriginGC() {
        val doc = applyGCOriginFixture(
            WireCompatFixtures.GC_ORIGIN_NESTED_TEXT_ORIGIN_GC_FULL_UPDATE_A,
            WireCompatFixtures.GC_ORIGIN_NESTED_TEXT_ORIGIN_GC_UPDATE_BPENDING
        )
        val map = doc.getMap("map")
        assertEquals("replaced", map.get("doc"))
    }

    @Test
    fun testNestedArrayRightOriginGC() {
        val doc = applyGCOriginFixture(
            WireCompatFixtures.GC_ORIGIN_NESTED_ARRAY_RIGHT_ORIGIN_GC_FULL_UPDATE_A,
            WireCompatFixtures.GC_ORIGIN_NESTED_ARRAY_RIGHT_ORIGIN_GC_UPDATE_BPENDING
        )
        val arr = doc.getArray("arr")
        assertEquals(0, arr.length)
    }

    @Test
    fun testNestedArrayBothOriginsGC() {
        val doc = applyGCOriginFixture(
            WireCompatFixtures.GC_ORIGIN_NESTED_ARRAY_BOTH_ORIGINS_GC_FULL_UPDATE_A,
            WireCompatFixtures.GC_ORIGIN_NESTED_ARRAY_BOTH_ORIGINS_GC_UPDATE_BPENDING
        )
        val arr = doc.getArray("arr")
        assertEquals(0, arr.length)
    }
}
