@file:OptIn(ExperimentalUuidApi::class)

package bosca.localization.export

import bosca.localization.model.ExportFormat
import bosca.localization.model.ExportResult
import bosca.localization.model.LocalizationPluralTranslation
import bosca.localization.model.LocalizationString
import bosca.localization.model.LocalizationTranslation
import bosca.localization.placeholder.PlaceholderConverter
import bosca.serialization.UUID
import kotlin.uuid.ExperimentalUuidApi

/**
 * iOS `.strings` file exporter for plain (non-plural) translations.
 *
 * Plural strings are intentionally skipped here; iOS uses the separate
 * `.stringsdict` plist format for plural forms, produced by [IosStringsdictExporter].
 * When an iOS consumer needs both, export twice (once per format) and ship both files.
 *
 * ICU placeholders are rewritten to iOS specifiers (`%@` for strings, `%d`/`%f` for numbers).
 */
class IosStringsExporter : LocalizationExporter {

    override val format: ExportFormat = ExportFormat.IOS_STRINGS

    override suspend fun export(
        languageTag: String,
        strings: List<LocalizationString>,
        translations: Map<UUID, LocalizationTranslation>,
        pluralTranslations: Map<UUID, List<LocalizationPluralTranslation>>,
        sourceLanguage: String,
        sourceTranslations: Map<UUID, LocalizationTranslation>
    ): ExportResult {
        val sb = StringBuilder()
        sb.appendLine("/* Localized strings generated by Bosca localization. Language: $languageTag */")
        for (string in strings) {
            if (string.plural) continue
            val translation = translations[string.id] ?: continue
            val converted = PlaceholderConverter.toIos(translation.text)
            sb.appendLine("\"${escape(string.key)}\" = \"${escape(converted)}\";")
        }
        return ExportResult(
            content = sb.toString(),
            contentType = "text/plain",
            fileName = "$languageTag.lproj/Localizable.strings"
        )
    }

    private fun escape(source: String): String = source
        .replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("\n", "\\n")
}
