package bosca.scheduler

import bosca.queue.annotations.IJobDefinition
import java.util.concurrent.CopyOnWriteArrayList
import kotlin.reflect.KClass

data class SchedulableJob(
    val clazz: KClass<out IJobDefinition>,
    val name: String,
    val description: String
)

/**
 * Provides a list of [SchedulableJob] definitions that can be registered with the
 * [SchedulableJobRegistry].
 *
 * Implementations are typically generated by KSP from [@JobDefinition][bosca.queue.annotations.IJobDefinition]
 * annotations and supply the job metadata (class, name, description) for each schedulable job
 * in their module.
 */
interface SchedulableJobRegistrar {
    /**
     * Returns the schedulable jobs contributed by this registrar.
     *
     * @return a list of [SchedulableJob] definitions
     */
    fun getSchedulableJobs(): List<SchedulableJob>
}

object SchedulableJobRegistry {
    private val jobs = CopyOnWriteArrayList<SchedulableJob>()

    fun getSchedulableJobs(): List<SchedulableJob> = jobs.toList()

    fun register(vararg registrars: SchedulableJobRegistrar) {
        registrars.forEach { registrar ->
            jobs.addAll(registrar.getSchedulableJobs())
        }
    }
}
