package bosca.graphql.codegen

import bosca.graphql.parser.Parser
import bosca.graphql.schema.GraphQLSchema
import kotlin.test.Test
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/** The reachable failure paths shared by both client generators (multiple operations, no root, unknown field, …). */
class GeneratorEdgeCasesTest {

    private val schema = GraphQLSchema.fromSdl(
        """
        type Query { me: User node: Node }
        type User implements Node { id: ID! name: String! }
        interface Node { id: ID! }
        """.trimIndent(),
    )

    private fun ts(query: String) = TypeScriptClientGenerator(schema).generate(Parser.parse(query))
    private fun kt(query: String) = KotlinClientGenerator(schema).generate(Parser.parse(query), "p")

    @Test
    fun `a document with more than one operation is rejected`() {
        assertFailsWith<IllegalStateException> { ts("query A { me { id } } query B { me { id } }") }
        assertFailsWith<IllegalStateException> { kt("query A { me { id } } query B { me { id } }") }
    }

    @Test
    fun `a subscription is rejected by TypeScript but generated by Kotlin`() {
        val withSub = GraphQLSchema.fromSdl("type Query { a: String } type Subscription { t: Int }")
        assertFailsWith<IllegalArgumentException> { TypeScriptClientGenerator(withSub).generate(Parser.parse("subscription S { t }")) }
        // Kotlin generates the typed operation regardless of type; the transport is the caller's concern.
        assertTrue("object S : BoscaOperation" in KotlinClientGenerator(withSub).generate(Parser.parse("subscription S { t }"), "p"))
    }

    @Test
    fun `an anonymous operation is rejected`() {
        assertFailsWith<IllegalStateException> { ts("{ me { id } }") }
        assertFailsWith<IllegalStateException> { kt("{ me { id } }") }
    }

    @Test
    fun `the TS generator rejects a mutation with no mutation root`() {
        // TS supports query + mutation, so it reaches the missing-root check
        assertFailsWith<IllegalStateException> { ts("mutation M { me { id } }") }
    }

    @Test
    fun `the Kotlin generator generates a mutation, and rejects one with no mutation root`() {
        val withMut = GraphQLSchema.fromSdl("type Query { a: String } type Mutation { save(x: Int): Int }")
        assertTrue("object Save : BoscaOperation" in KotlinClientGenerator(withMut).generate(Parser.parse("mutation Save(\$x: Int) { save(x: \$x) }"), "p"))
        // this schema has no mutation root → the missing-root guard fires
        assertFailsWith<IllegalStateException> { kt("mutation M { me { id } }") }
    }

    @Test
    fun `an unknown field is rejected`() {
        assertFailsWith<IllegalStateException> { ts("query Q { bogus }") }
        assertFailsWith<IllegalStateException> { kt("query Q { bogus }") }
    }

    @Test
    fun `valid queries with every nullability and a nested object still generate`() {
        // positive companion: exercises required/optional/nested type-ref rendering on both generators
        val q = "query Q { me { id name } }"
        assertTrue(ts(q).contains("export interface QData"))
        assertTrue(kt(q).contains("data class QData"))
    }
}
