apiVersion: v2
name: bosca-runner
description: Bosca background job runner with configurable worker deployments
type: application
version: 0.1.0
appVersion: "5.0.21"
dependencies:
  - name: bosca-common
    version: ">=0.1.0"
    repository: "file://../bosca-common"
