package bosca.cli.service

import bosca.cli.BoscaCliCommand
import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.types.int
import java.io.File

class ServiceInstallCommand : BoscaCliCommand(name = "install") {
    override fun help(context: Context) = "Install bosca as a system service with auto-restart"

    private val command by option(
        "--command",
        help = "The bosca subcommand to run as a service (e.g. 'ci agent start', 'mcp-server')"
    ).default("ci agent start")

    private val serviceName by option(
        "--name",
        help = "Service name identifier"
    ).default("bosca")

    private val restartDelay by option(
        "--restart-delay",
        help = "Seconds to wait before restarting on failure"
    ).int().default(5)

    private val envFile by option(
        "--env-file",
        help = "Path to an environment file (key=value per line) to load into the service. " +
            "If not provided, one is auto-generated by discovering SDKMAN, nvm, and other tool managers."
    )

    private val system by option(
        "--system",
        help = "Install as system-wide service (requires root/sudo)"
    )

    override fun run() {
        val boscaPath = resolveBoscaExecutable()
        val os = System.getProperty("os.name").lowercase()

        when {
            os.contains("mac") || os.contains("darwin") -> installLaunchd(boscaPath)
            os.contains("linux") -> installSystemd(boscaPath)
            else -> throw CliktError("Unsupported platform: $os. Only macOS (launchd) and Linux (systemd) are supported.")
        }
    }

    private fun resolveEnvFile(): File {
        if (envFile != null) {
            val file = File(envFile!!)
            if (!file.exists()) throw CliktError("Environment file not found: $envFile")
            return file
        }
        val configDir = File(System.getProperty("user.home"), ".config/bosca")
        configDir.mkdirs()
        val generatedFile = File(configDir, "$serviceName.env")
        val env = discoverEnvironment()
        generatedFile.writeText(env.entries.joinToString("\n") { "${it.key}=${it.value}" } + "\n")
        echo("Generated environment file: ${generatedFile.absolutePath}")
        for ((key, value) in env) {
            echo("  $key=$value")
        }
        return generatedFile
    }

    private fun discoverEnvironment(): LinkedHashMap<String, String> {
        val home = System.getProperty("user.home")
        val env = LinkedHashMap<String, String>()
        val extraPaths = mutableListOf<String>()

        discoverSdkman(home, env, extraPaths)
        discoverNvm(home, env, extraPaths)
        discoverPyenv(home, extraPaths)
        discoverRbenv(home, extraPaths)
        discoverGoenv(home, env, extraPaths)
        discoverRustup(home, extraPaths)
        discoverAndroidSdk(home, env, extraPaths)

        val basePath = "/usr/local/bin:/usr/bin:/bin"
        val path = if (extraPaths.isNotEmpty()) {
            extraPaths.joinToString(":") + ":$basePath"
        } else {
            basePath
        }
        env["PATH"] = path
        return env
    }

    private fun discoverSdkman(home: String, env: LinkedHashMap<String, String>, extraPaths: MutableList<String>) {
        val sdkmanDir = File(home, ".sdkman")
        if (!sdkmanDir.isDirectory) return

        val candidatesDir = File(sdkmanDir, "candidates")
        if (!candidatesDir.isDirectory) return

        val candidates = candidatesDir.listFiles()?.filter { it.isDirectory } ?: return
        for (candidate in candidates) {
            val currentLink = File(candidate, "current")
            if (!currentLink.exists()) continue

            val resolved = currentLink.canonicalFile
            val binDir = File(resolved, "bin")
            if (binDir.isDirectory) {
                extraPaths.add(binDir.absolutePath)
            }

            val envVar = when (candidate.name) {
                "java" -> "JAVA_HOME"
                "gradle" -> "GRADLE_HOME"
                "maven" -> "MAVEN_HOME"
                "kotlin" -> "KOTLIN_HOME"
                "scala" -> "SCALA_HOME"
                "groovy" -> "GROOVY_HOME"
                else -> null
            }
            if (envVar != null) {
                env[envVar] = resolved.absolutePath
            }
        }

        env["SDKMAN_DIR"] = sdkmanDir.absolutePath
    }

    private fun discoverNvm(home: String, env: LinkedHashMap<String, String>, extraPaths: MutableList<String>) {
        val nvmDir = File(home, ".nvm")
        if (!nvmDir.isDirectory) return

        val currentAlias = File(nvmDir, "alias/default")
        if (!currentAlias.exists()) return

        val version = currentAlias.readText().trim()
        val versionDirs = File(nvmDir, "versions/node").listFiles()?.filter { it.isDirectory } ?: return

        val match = versionDirs.find { it.name == version || it.name == "v$version" }
            ?: versionDirs.lastOrNull()

        if (match != null) {
            val binDir = File(match, "bin")
            if (binDir.isDirectory) {
                extraPaths.add(binDir.absolutePath)
                env["NODE_HOME"] = match.absolutePath
            }
        }

        env["NVM_DIR"] = nvmDir.absolutePath
    }

    private fun discoverPyenv(home: String, extraPaths: MutableList<String>) {
        val pyenvDir = File(home, ".pyenv")
        if (!pyenvDir.isDirectory) return

        val shimsDir = File(pyenvDir, "shims")
        if (shimsDir.isDirectory) {
            extraPaths.add(shimsDir.absolutePath)
        }
    }

    private fun discoverRbenv(home: String, extraPaths: MutableList<String>) {
        val rbenvDir = File(home, ".rbenv")
        if (!rbenvDir.isDirectory) return

        val shimsDir = File(rbenvDir, "shims")
        if (shimsDir.isDirectory) {
            extraPaths.add(shimsDir.absolutePath)
        }
    }

    private fun discoverGoenv(home: String, env: LinkedHashMap<String, String>, extraPaths: MutableList<String>) {
        val goDir = File(home, "go")
        if (!goDir.isDirectory) {
            val goPath = File(home, ".go")
            if (!goPath.isDirectory) return
            val binDir = File(goPath, "bin")
            if (binDir.isDirectory) extraPaths.add(binDir.absolutePath)
            return
        }

        val binDir = File(goDir, "bin")
        if (binDir.isDirectory) {
            extraPaths.add(binDir.absolutePath)
            env["GOPATH"] = goDir.absolutePath
        }
    }

    private fun discoverAndroidSdk(home: String, env: LinkedHashMap<String, String>, extraPaths: MutableList<String>) {
        val candidates = listOf(
            File(home, "Library/Android/sdk"),
            File(home, "Android/Sdk"),
            File(home, ".android/sdk"),
        )
        val sdkDir = candidates.firstOrNull { it.isDirectory } ?: return
        env["ANDROID_HOME"] = sdkDir.absolutePath
        val platformTools = File(sdkDir, "platform-tools")
        if (platformTools.isDirectory) extraPaths.add(platformTools.absolutePath)
        val cmdlineTools = File(sdkDir, "cmdline-tools/latest/bin")
        if (cmdlineTools.isDirectory) extraPaths.add(cmdlineTools.absolutePath)
    }

    private fun discoverRustup(home: String, extraPaths: MutableList<String>) {
        val cargoDir = File(home, ".cargo")
        if (!cargoDir.isDirectory) return

        val binDir = File(cargoDir, "bin")
        if (binDir.isDirectory) {
            extraPaths.add(binDir.absolutePath)
        }
    }

    private fun installLaunchd(boscaPath: String) {
        val label = "io.bosca.$serviceName"
        val commandArgs = command.split(" ")
        val plistDir = if (system != null) {
            File("/Library/LaunchDaemons")
        } else {
            File(System.getProperty("user.home"), "Library/LaunchAgents")
        }
        plistDir.mkdirs()
        val plistFile = File(plistDir, "$label.plist")

        val programArgs = buildList {
            add(boscaPath)
            addAll(commandArgs)
        }

        val programArgsXml = programArgs.joinToString("\n") { "        <string>$it</string>" }

        val envFileResolved = resolveEnvFile()
        val envVars = parseEnvFile(envFileResolved)
        val envXml = envVars.entries.joinToString("\n") {
            "        <key>${it.key}</key>\n        <string>${it.value}</string>"
        }

        val plist = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$label</string>
    <key>ProgramArguments</key>
    <array>
$programArgsXml
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>ThrottleInterval</key>
    <integer>$restartDelay</integer>
    <key>StandardOutPath</key>
    <string>/tmp/$label.out.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/$label.err.log</string>
    <key>EnvironmentVariables</key>
    <dict>
$envXml
    </dict>
</dict>
</plist>
"""
        plistFile.writeText(plist)
        echo("Wrote plist: ${plistFile.absolutePath}")

        val loadResult = ProcessBuilder("launchctl", "load", "-w", plistFile.absolutePath)
            .redirectErrorStream(true)
            .start()
        val output = loadResult.inputStream.bufferedReader().readText().trim()
        val exitCode = loadResult.waitFor()

        if (exitCode != 0) {
            echo("Warning: launchctl load returned $exitCode: $output", err = true)
            echo("You may need to load it manually: launchctl load -w ${plistFile.absolutePath}")
        } else {
            echo("Service loaded and started.")
        }

        echo("")
        echo("Service installed: $label")
        echo("  Env:     ${envFileResolved.absolutePath}")
        echo("  Logs:    /tmp/$label.out.log, /tmp/$label.err.log")
        echo("  Stop:    launchctl unload ${plistFile.absolutePath}")
        echo("  Start:   launchctl load -w ${plistFile.absolutePath}")
        echo("  Status:  launchctl list | grep $label")
    }

    private fun installSystemd(boscaPath: String) {
        val commandArgs = command.split(" ").joinToString(" ")
        val isSystem = system != null
        val unitDir = if (isSystem) {
            File("/etc/systemd/system")
        } else {
            val configDir = System.getenv("XDG_CONFIG_HOME")
                ?: "${System.getProperty("user.home")}/.config"
            File(configDir, "systemd/user")
        }
        unitDir.mkdirs()
        val unitFile = File(unitDir, "$serviceName.service")

        val envFileResolved = resolveEnvFile()

        val unit = """[Unit]
Description=Bosca service ($serviceName)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$boscaPath $commandArgs
Restart=on-failure
RestartSec=$restartDelay
EnvironmentFile=${envFileResolved.absolutePath}

[Install]
WantedBy=${if (isSystem) "multi-user.target" else "default.target"}
"""
        unitFile.writeText(unit)
        echo("Wrote unit file: ${unitFile.absolutePath}")

        val systemctlArgs = if (isSystem) {
            listOf("systemctl", "daemon-reload")
        } else {
            listOf("systemctl", "--user", "daemon-reload")
        }
        val reloadResult = ProcessBuilder(systemctlArgs)
            .redirectErrorStream(true)
            .start()
        reloadResult.waitFor()

        val enableArgs = if (isSystem) {
            listOf("systemctl", "enable", "--now", "$serviceName.service")
        } else {
            listOf("systemctl", "--user", "enable", "--now", "$serviceName.service")
        }
        val enableResult = ProcessBuilder(enableArgs)
            .redirectErrorStream(true)
            .start()
        val output = enableResult.inputStream.bufferedReader().readText().trim()
        val exitCode = enableResult.waitFor()

        if (exitCode != 0) {
            echo("Warning: systemctl enable returned $exitCode: $output", err = true)
            val scope = if (isSystem) "" else " --user"
            echo("You may need to run manually: systemctl$scope enable --now $serviceName.service")
        } else {
            echo("Service enabled and started.")
        }

        val scope = if (isSystem) "" else " --user"
        echo("")
        echo("Service installed: $serviceName.service")
        echo("  Env:     ${envFileResolved.absolutePath}")
        echo("  Status:  systemctl$scope status $serviceName")
        echo("  Logs:    journalctl$scope -u $serviceName -f")
        echo("  Stop:    systemctl$scope stop $serviceName")
        echo("  Restart: systemctl$scope restart $serviceName")
    }

    private fun parseEnvFile(file: File): Map<String, String> {
        return file.readLines()
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .mapNotNull { line ->
                val eq = line.indexOf('=')
                if (eq > 0) line.substring(0, eq) to line.substring(eq + 1) else null
            }
            .toMap()
    }

    private fun resolveBoscaExecutable(): String {
        val command = ProcessHandle.current().info().command().orElse(null)
        if (command != null) return command
        val which = ProcessBuilder("which", "bosca")
            .redirectErrorStream(true)
            .start()
        val path = which.inputStream.bufferedReader().readText().trim()
        if (which.waitFor() == 0 && path.isNotEmpty()) return path
        throw CliktError("Cannot locate the bosca executable. Ensure it is on your PATH.")
    }
}
