package bosca.serialization

import kotlinx.serialization.KSerializer
import java.util.concurrent.ConcurrentHashMap

/**
 * Serializer cache for GraalVM native image compatibility.
 *
 * kotlinx.serialization's reflective `KClass.serializer()` lookup fails in native images
 * because the reflection chain is unreliable. This cache bypasses that problem by storing
 * serializers resolved via direct compiled calls (e.g., `Document.serializer()`), which
 * are generated by KSP into [SerializerRegistrar] implementations.
 *
 * At application startup, each module's generated `ProviderRegistrar` calls its
 * `SerializerRegistrar.register()`, populating this cache with every `@Serializable`
 * type's serializer. Runtime code then queries [get] instead of using reflection.
 */
object SerializerCache {

    private val cache = ConcurrentHashMap<Class<*>, KSerializer<*>>()
    private val bySerialName = ConcurrentHashMap<String, KSerializer<*>>()
    private val classesByTypeName = ConcurrentHashMap<String, Class<*>>()
    private val cataloguedTypeNames = ConcurrentHashMap.newKeySet<String>()

    /**
     * Stores a pre-resolved serializer for the given class.
     * Called by KSP-generated [SerializerRegistrar] implementations.
     */
    @JvmStatic
    fun register(clazz: Class<*>, serializer: KSerializer<*>, vararg assignableTypes: Class<*>) {
        cache[clazz] = serializer
        bySerialName[serializer.descriptor.serialName] = serializer
        classesByTypeName[clazz.name] = clazz
        classesByTypeName[serializer.descriptor.serialName] = clazz
        cataloguedTypeNames += serializer.descriptor.serialName
        for (type in assignableTypes) {
            classesByTypeName[type.name] = type
            if (type.isCataloguedSupertype()) cataloguedTypeNames += type.name
        }
    }

    /**
     * Returns a pre-resolved serializer for the given class, or `null` if none was
     * registered.
     */
    @Suppress("UNCHECKED_CAST")
    fun <T> get(clazz: Class<T>): KSerializer<T>? {
        return cache[clazz] as? KSerializer<T>
    }

    /**
     * Returns the registered serializer whose descriptor's serial name is [serialName], for callers
     * that hold only a type's *name* — e.g. a pipeline Cast node casting JSON to a catalogued type.
     * Falls back to resolving the class by that name (a serial name defaults to the FQCN) and caching
     * the result; the fallback is JVM-only reach — under a native image, only registered serializers
     * (and classes in the reflection config) resolve.
     */
    fun get(serialName: String): KSerializer<*>? {
        bySerialName[serialName]?.let { return it }
        val clazz = classFor(serialName) ?: return null
        return resolveSerializerOrNull(clazz.kotlin)?.also { bySerialName[serialName] = it }
    }

    /**
     * Returns the JVM class represented by [typeName]. Both a serializer's declared serial name and
     * the fully-qualified names of its KSP-registered supertypes resolve here. This lets native-safe
     * consumers perform ordinary [Class.isAssignableFrom] / [Class.isInstance] checks without classpath
     * scanning or reflective serializer discovery.
     */
    fun classFor(typeName: String): Class<*>? {
        classesByTypeName[typeName]?.let { return it }
        val clazz = try {
            Class.forName(typeName)
        } catch (e: ClassNotFoundException) {
            return null
        } catch (e: LinkageError) {
            return null
        }
        classesByTypeName[typeName] = clazz
        return clazz
    }

    /**
     * Every registered serializable type plus its non-platform supertypes, using the exact names a
     * pipeline may declare. Concrete entries use their serializer serial name (honouring
     * `@SerialName`); interface/base entries use their fully-qualified class name.
     */
    fun cataloguedTypes(): List<String> = cataloguedTypeNames.sorted()

    private fun Class<*>.isCataloguedSupertype(): Boolean =
        this != Any::class.java &&
            !name.startsWith("java.") &&
            !name.startsWith("javax.") &&
            !name.startsWith("kotlin.") &&
            !name.startsWith("kotlinx.")
}
