{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bosca-common.fullname" . }}
  labels:
    {{- include "bosca-common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bosca-common.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}
