@file:OptIn(bosca.di.annotation.InternalDI::class)

package bosca.workops.service


import bosca.db.ConnectionConfig
import bosca.db.ConnectionFactoryImpl
import bosca.db.ConnectionPool
import bosca.db.asCoroutineContext
import bosca.db.connection
import bosca.db.migrations.FlywayMigration
import bosca.db.transaction
import bosca.di.ProviderRegistry
import bosca.di.provides
import bosca.security.service.SecurityService
import bosca.serialization.UUID
import bosca.db.migrations.CoreMigration
import bosca.workops.migration.WorkOpsMigration
import bosca.workops.model.bql.BqlField
import bosca.workops.model.bql.BqlFieldCatalog
import bosca.workops.model.bql.BqlFieldType
import bosca.workops.model.bql.BqlFunctionCatalog
import bosca.workops.model.bql.BqlFunctionResolver
import bosca.workops.model.bql.BqlNameResolver
import bosca.workops.model.bql.BqlParseException
import bosca.workops.model.bql.BqlPlanner
import bosca.workops.model.project.PortfolioInput
import bosca.workops.model.project.ProgramInput
import bosca.workops.model.project.ProjectInput
import bosca.workops.model.task.CreateTaskInput
import bosca.workops.model.task.UpdateTaskInput
import io.mockk.mockk
import bosca.di.asProvider
import bosca.workops.repository.PortfolioRepositoryImpl
import bosca.workops.repository.PriorityRepositoryImpl
import bosca.workops.repository.ProgramRepositoryImpl
import bosca.workops.repository.ProjectKeyCounterRepositoryImpl
import bosca.workops.repository.ProjectRepositoryImpl
import bosca.workops.repository.ResolutionRepositoryImpl
import bosca.workops.repository.SavedFilterRepositoryImpl
import bosca.workops.repository.StatusRepositoryImpl
import bosca.workops.repository.TaskFieldConfigurationRepositoryImpl
import bosca.workops.repository.TaskHistoryRepositoryImpl
import bosca.workops.repository.TaskRepositoryImpl
import bosca.workops.repository.TaskTypeRepositoryImpl
import bosca.workops.repository.TaskTypeSchemeRepositoryImpl
import bosca.workops.repository.PortfolioPermissionRepositoryImpl
import bosca.workops.repository.ProgramPermissionRepositoryImpl
import bosca.workops.repository.ProjectPermissionRepositoryImpl
import bosca.workops.repository.TaskPermissionRepositoryImpl
import bosca.workops.repository.TaskAffectedProjectRepositoryImpl
import bosca.workops.repository.WorkflowRepositoryImpl
import bosca.workops.repository.WorkflowSchemeRepositoryImpl
import kotlinx.coroutines.NonCancellable
import org.junit.AfterClass
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import bosca.test.resources.SharedPostgreSQLContainer
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * End-to-end integration test exercising [TaskQueryServiceImpl.search]
 * against a real PostgreSQL instance via TestContainers. The suite
 * proves that the hand-rolled [TaskQueryServiceImpl.bindParameter]
 * method correctly binds every [bosca.workops.model.bql.BqlBoundType]
 * variant to a real [java.sql.PreparedStatement]:
 *
 *   1. TEXT equality and ILIKE via `summary = "…"` / `summary ~ "…"`.
 *   2. NAME_REFERENCE resolution via `project = KEY` / `priority = Name`.
 *   3. UUID equality via `assignee = currentUser()`.
 *   4. TIMESTAMP comparison via `created > now()` / `dueDate < now()`.
 *   5. ORDER BY and LIMIT clauses generated by the planner.
 *   6. Compound AND / OR filters with multiple bound parameters.
 *
 * Each test seeds a small number of tasks and asserts that the dynamic
 * SQL round-trips through Postgres without JDBC type errors or silent
 * data corruption.
 */
class BqlSearchIntegrationTest {

    companion object {
        private val postgres = SharedPostgreSQLContainer("pgvector/pgvector:pg17").apply {
            withDatabaseName("bosca_workops_bql_search_test")
            withReuse(true)
            start()
        }
        private val pool = ConnectionPool(
            ConnectionFactoryImpl(
                ConnectionConfig(
                    url = postgres.jdbcUrl,
                    user = postgres.username,
                    password = postgres.password,
                    maxConnections = 5,
                ),
                key = "workops-bql-search-test",
            )
        )
        private var schemaInitialized = false

        @AfterClass
        @JvmStatic
        fun shutdown() {
            runBlocking {
                pool.close()
            }
            postgres.stop()
        }
    }

    private val json = Json { ignoreUnknownKeys = true }

    private val portfolioRepo = PortfolioRepositoryImpl()
    private val portfolioPermissionRepo = PortfolioPermissionRepositoryImpl()
    private val programRepo = ProgramRepositoryImpl()
    private val programPermissionRepo = ProgramPermissionRepositoryImpl()
    private val projectRepo = ProjectRepositoryImpl()
    private val projectPermissionRepo = ProjectPermissionRepositoryImpl()
    private val keyCounterRepo = ProjectKeyCounterRepositoryImpl()
    private val taskTypeRepo = TaskTypeRepositoryImpl()
    private val taskTypeSchemeRepo = TaskTypeSchemeRepositoryImpl()
    private val statusRepo = StatusRepositoryImpl()
    private val priorityRepo = PriorityRepositoryImpl()
    private val resolutionRepo = ResolutionRepositoryImpl()
    private val taskRepo = TaskRepositoryImpl()
    private val taskPermissionRepo = TaskPermissionRepositoryImpl()
    private val historyRepo = TaskHistoryRepositoryImpl()
    private val workflowRepo = WorkflowRepositoryImpl()
    private val schemeRepo = WorkflowSchemeRepositoryImpl()
    private val fieldConfigRepo = TaskFieldConfigurationRepositoryImpl()
    private val workflowQueryRepo = WorkflowQueryRepositoryImpl()
    private val affectedRepo = TaskAffectedProjectRepositoryImpl()

    private val securityService = mockk<SecurityService>(relaxed = true)
    private val portfolioService = PortfolioServiceImpl(portfolioRepo, portfolioPermissionRepo, securityService)
    private val groupEvaluator = bosca.security.service.GroupEvaluator(securityService)
    private val portfolioPermissionEvaluator = PortfolioPermissionEvaluator(portfolioService, securityService, groupEvaluator)
    private val programService = ProgramServiceImpl(programRepo, portfolioRepo, programPermissionRepo, portfolioPermissionRepo, portfolioPermissionEvaluator)
    private val programPermissionEvaluator = ProgramPermissionEvaluator(programService, securityService, groupEvaluator)
    private val projectService = ProjectServiceImpl(projectRepo, programRepo, keyCounterRepo, projectPermissionRepo, programPermissionRepo, programPermissionEvaluator)
    private val projectPermissionEvaluator = ProjectPermissionEvaluator(projectService, securityService, groupEvaluator)
    private val workflowService = WorkflowServiceImpl(workflowRepo, schemeRepo, projectService, workflowQueryRepo)
    private val customFieldService = TaskCustomFieldServiceImpl(fieldConfigRepo)
    private val affectedService = TaskAffectedProjectServiceImpl(affectedRepo)
    private val taskService = TaskServiceImpl(
        taskRepository = taskRepo,
        taskHistoryRepository = historyRepo,
        projectService = projectService,
        programService = programService,
        taskTypeService = TaskTypeServiceImpl(taskTypeRepo),
        taskTypeSchemeService = TaskTypeSchemeServiceImpl(taskTypeSchemeRepo),
        statusService = StatusServiceImpl(statusRepo),
        priorityService = PriorityServiceImpl(priorityRepo),
        workflowService = workflowService,
        workflowEvaluator = WorkflowEvaluator(),
        customFieldService = customFieldService,
        json = json,
        taskPermissionRepository = taskPermissionRepo,
        affectedProjectService = affectedService,
        requirementServiceProvider = mockk<RequirementService>(relaxed = true).asProvider(),
        metadataService = mockk(relaxed = true),
        sprintService = mockk(relaxed = true),
        projectPermissionEvaluator = projectPermissionEvaluator,
    )
    private val taskQueryService = TaskQueryServiceImpl(
        priorityRepository = priorityRepo,
        statusRepository = statusRepo,
        taskTypeRepository = taskTypeRepo,
        resolutionRepository = resolutionRepo,
        projectRepository = projectRepo,
    )

    @BeforeTest
    fun setup() {
        ProviderRegistry.clear()
        provides<ConnectionPool>(singleton = true) { pool }
        provides<Json>(singleton = true) { json }
        provides<bosca.pubsub.PubSubService>(singleton = true) { mockk(relaxed = true) }
        provides<bosca.sharedqueue.jobs.JobQueue>(name = "workops", singleton = true) { mockk(relaxed = true) }
        if (!schemaInitialized) {
            runBlocking { FlywayMigration(pool).migrate(listOf(CoreMigration(), WorkOpsMigration())) }
            schemaInitialized = true
        }
        withDb {
            transaction {
                connection().useStatement("DELETE FROM workops.saved_filter") { it.execute() }
                connection().useStatement("DELETE FROM workops.task_history") { it.execute() }
                connection().useStatement("DELETE FROM workops.task") { it.execute() }
                connection().useStatement("DELETE FROM workops.project_key_counter") { it.execute() }
                connection().useStatement("DELETE FROM workops.project") { it.execute() }
                connection().useStatement("DELETE FROM workops.program") { it.execute() }
                connection().useStatement("DELETE FROM workops.portfolio") { it.execute() }
            }
        }
    }

    private fun withDb(block: suspend () -> Unit) = runBlocking {
        val mgr = pool.connection()
        try {
            withContext(mgr.asCoroutineContext()) { block() }
        } finally {
            withContext(NonCancellable) { mgr.release() }
        }
    }

    private val ownerId: UUID = UUID.parse("11111111-1111-1111-1111-111111111111")
    private val callerPrincipalId: UUID = UUID.parse("22222222-2222-2222-2222-222222222222")
    private val callerProfileId: UUID = UUID.parse("33333333-3333-3333-3333-333333333333")
    private val otherProfileId: UUID = UUID.parse("44444444-4444-4444-4444-444444444444")

    private suspend fun seedProject(key: String = "BQS"): UUID {
        val portfolio = portfolioService.create(
            PortfolioInput(key = key, name = "$key Portfolio", description = null, ownerProfileId = ownerId)
        )
        val program = programService.create(
            ProgramInput(
                portfolioId = portfolio.id, key = "${key}P", name = "$key Program",
                description = null, ownerProfileId = ownerId,
            )
        )
        val project = projectService.create(
            ProjectInput(
                programId = program.id, key = key, name = "$key Project",
                description = null, ownerProfileId = ownerId,
            )
        )
        return project.id
    }

    private suspend fun createTask(
        projectId: UUID,
        summary: String,
        assigneeProfileId: UUID? = null,
        dueDate: bosca.serialization.OffsetDateTime? = null,
        startDate: bosca.serialization.OffsetDateTime? = null,
    ) = taskService.create(
        CreateTaskInput(
            projectId = projectId,
            summary = summary,
            assigneeProfileId = assigneeProfileId,
            dueDate = dueDate,
            startDate = startDate,
        ),
        actingPrincipalId = callerPrincipalId,
        actingProfileId = callerProfileId,
        reporterProfileId = callerProfileId,
    )

    // ---------------------------------------------------------------
    // TEXT equality — binds BqlBoundType.TEXT via PreparedStatement.setString
    // ---------------------------------------------------------------

    @Test
    fun `text equality filters on exact summary match`() = withDb {
        val projectId = seedProject()
        val target = createTask(projectId, "unique-needle-xyz")
        createTask(projectId, "unrelated task")

        val result = taskQueryService.search(
            """summary = "unique-needle-xyz"""",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(target.id, result.rows.single().id)
    }

    @Test
    fun `text inequality excludes matching summary`() = withDb {
        val projectId = seedProject()
        createTask(projectId, "exclude-me")
        val kept = createTask(projectId, "keep-me")

        val result = taskQueryService.search(
            """summary != "exclude-me"""",
            actingProfileId = callerProfileId,
        )
        val ids = result.rows.map { it.id }
        assertTrue(kept.id in ids)
        assertTrue(result.rows.none { it.summary == "exclude-me" })
    }

    // ---------------------------------------------------------------
    // TEXT ILIKE — binds BqlBoundType.TEXT via setString with % wrapping
    // ---------------------------------------------------------------

    @Test
    fun `text like performs case-insensitive substring search`() = withDb {
        val projectId = seedProject()
        val target = createTask(projectId, "Deploy the WIDGET today")
        createTask(projectId, "nothing relevant")

        val result = taskQueryService.search(
            """summary ~ "widget"""",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(target.id, result.rows.single().id)
        assertEquals(listOf("widget"), result.freeTextTerms)
    }

    // ---------------------------------------------------------------
    // NAME_REFERENCE — resolves a name to UUID then binds BqlBoundType.UUID
    // ---------------------------------------------------------------

    @Test
    fun `name reference resolves project key to UUID`() = withDb {
        val projectId = seedProject("NRF")
        val t1 = createTask(projectId, "in-project")

        val result = taskQueryService.search(
            "project = NRF",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(t1.id, result.rows.single().id)
    }

    @Test
    fun `name reference resolves priority by name`() = withDb {
        val projectId = seedProject("PRI")
        val t1 = createTask(projectId, "task-a")
        val t2 = createTask(projectId, "task-b")

        // Both tasks share the same default priority (Medium). Searching
        // by that name should return both.
        val result = taskQueryService.search(
            "priority = Medium",
            actingProfileId = callerProfileId,
        )
        val ids = result.rows.map { it.id }.toSet()
        assertTrue(t1.id in ids)
        assertTrue(t2.id in ids)
    }

    @Test
    fun `name references resolve task type status and resolution catalogs`() = withDb {
        val projectId = seedProject("NRC")
        val task = createTask(projectId, "catalog task")
        val taskType = taskTypeRepo.getAll().first { it.id == task.taskTypeId }
        val status = statusRepo.getAll().first { it.id == task.statusId }
        val resolution = resolutionRepo.getAll().first()

        assertEquals(
            task.id,
            taskQueryService.search("type = \"${taskType.name}\"", callerProfileId).rows.single().id,
        )
        assertEquals(
            task.id,
            taskQueryService.search("status = \"${status.name}\"", callerProfileId).rows.single().id,
        )
        assertTrue(taskQueryService.search("resolution = \"${resolution.name}\"", callerProfileId).rows.isEmpty())
    }

    @Test
    fun `unknown catalog names fail planning for every named task field`() = withDb {
        seedProject("MIS")

        listOf("priority", "status", "type", "resolution", "project").forEach { field ->
            kotlin.test.assertFailsWith<BqlParseException>("$field should reject an unknown catalog name") {
                taskQueryService.search("$field = definitely-missing", callerProfileId)
            }
        }
    }

    // ---------------------------------------------------------------
    // UUID — binds BqlBoundType.UUID via setObject(java.util.UUID)
    // ---------------------------------------------------------------

    @Test
    fun `uuid filter matches assignee profile id`() = withDb {
        val projectId = seedProject("UID")
        val mine = createTask(projectId, "mine", assigneeProfileId = callerProfileId)
        createTask(projectId, "theirs", assigneeProfileId = otherProfileId)

        val result = taskQueryService.search(
            "assignee = currentUser()",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(mine.id, result.rows.single().id)
    }

    @Test
    fun `uuid filter with literal uuid string`() = withDb {
        val projectId = seedProject("ULT")
        val mine = createTask(projectId, "mine", assigneeProfileId = callerProfileId)
        createTask(projectId, "other", assigneeProfileId = otherProfileId)

        val result = taskQueryService.search(
            """assignee = "$callerProfileId"""",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(mine.id, result.rows.single().id)
    }

    @Test
    fun `uuid inequality excludes matching assignee`() = withDb {
        val projectId = seedProject("UNE")
        createTask(projectId, "mine", assigneeProfileId = callerProfileId)
        val other = createTask(projectId, "other", assigneeProfileId = otherProfileId)

        val result = taskQueryService.search(
            "assignee != currentUser()",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(other.id, result.rows.single().id)
    }

    // ---------------------------------------------------------------
    // TIMESTAMP — binds BqlBoundType.TIMESTAMP via setTimestamp
    // ---------------------------------------------------------------

    @Test
    fun `timestamp filter with created less-than future returns all tasks`() = withDb {
        val projectId = seedProject("TSF")
        createTask(projectId, "alpha")
        createTask(projectId, "beta")

        // All tasks have created_at in the past, so created < endOfWeek()
        // should match them all.
        val result = taskQueryService.search(
            "created < endOfWeek()",
            actingProfileId = callerProfileId,
        )
        assertTrue(result.rows.size >= 2, "expected at least 2 tasks, got ${result.rows.size}")
    }

    @Test
    fun `timestamp filter with created greater-than far-future returns nothing`() = withDb {
        val projectId = seedProject("TSN")
        createTask(projectId, "task-one")

        // Use a future timestamp literal that is clearly after all seeded tasks.
        val result = taskQueryService.search(
            """created > "2099-01-01T00:00:00Z"""",
            actingProfileId = callerProfileId,
        )
        assertEquals(0, result.rows.size)
    }

    @Test
    fun `timestamp filter with dueDate set on task`() = withDb {
        val projectId = seedProject("TSD")
        val farFuture = bosca.serialization.OffsetDateTime.parse("2099-06-15T12:00:00Z")
        val target = createTask(projectId, "future-due", dueDate = farFuture)
        createTask(projectId, "no-due")

        val result = taskQueryService.search(
            """dueDate > "2099-01-01T00:00:00Z"""",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(target.id, result.rows.single().id)
    }

    // ---------------------------------------------------------------
    // ORDER BY — planner emits column + direction, no parameter binding
    // ---------------------------------------------------------------

    @Test
    fun `order by summary ascending sorts results`() = withDb {
        val projectId = seedProject("ORD")
        createTask(projectId, "charlie")
        createTask(projectId, "alpha")
        createTask(projectId, "bravo")

        val result = taskQueryService.search(
            "project = ORD ORDER BY summary ASC",
            actingProfileId = callerProfileId,
        )
        assertEquals(3, result.rows.size)
        assertEquals(listOf("alpha", "bravo", "charlie"), result.rows.map { it.summary })
    }

    @Test
    fun `order by summary descending sorts results`() = withDb {
        val projectId = seedProject("ODS")
        createTask(projectId, "charlie")
        createTask(projectId, "alpha")
        createTask(projectId, "bravo")

        val result = taskQueryService.search(
            "project = ODS ORDER BY summary DESC",
            actingProfileId = callerProfileId,
        )
        assertEquals(3, result.rows.size)
        assertEquals(listOf("charlie", "bravo", "alpha"), result.rows.map { it.summary })
    }

    // ---------------------------------------------------------------
    // LIMIT — the search method clamps and binds limit / offset
    // ---------------------------------------------------------------

    @Test
    fun `limit restricts result count`() = withDb {
        val projectId = seedProject("LIM")
        createTask(projectId, "a")
        createTask(projectId, "b")
        createTask(projectId, "c")

        val result = taskQueryService.search(
            "project = LIM ORDER BY summary ASC",
            actingProfileId = callerProfileId,
            offset = 0,
            limit = 2,
        )
        assertEquals(2, result.rows.size)
    }

    @Test
    fun `offset skips leading rows`() = withDb {
        val projectId = seedProject("OFF")
        createTask(projectId, "a")
        createTask(projectId, "b")
        createTask(projectId, "c")

        val result = taskQueryService.search(
            "project = OFF ORDER BY summary ASC",
            actingProfileId = callerProfileId,
            offset = 1,
            limit = 50,
        )
        assertEquals(2, result.rows.size)
        assertEquals("b", result.rows.first().summary)
    }

    // ---------------------------------------------------------------
    // Compound AND / OR — multiple bound parameters in one query
    // ---------------------------------------------------------------

    @Test
    fun `compound AND narrows results to intersection`() = withDb {
        val projectId = seedProject("AND")
        val target = createTask(projectId, "alpha", assigneeProfileId = callerProfileId)
        createTask(projectId, "beta", assigneeProfileId = otherProfileId)
        createTask(projectId, "alpha-other", assigneeProfileId = otherProfileId)

        val result = taskQueryService.search(
            """summary = "alpha" AND assignee = currentUser()""",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(target.id, result.rows.single().id)
    }

    @Test
    fun `compound OR widens results to union`() = withDb {
        val projectId = seedProject("ORA")
        val a = createTask(projectId, "apple")
        val b = createTask(projectId, "banana")
        createTask(projectId, "cherry")

        val result = taskQueryService.search(
            """summary = "apple" OR summary = "banana"""",
            actingProfileId = callerProfileId,
        )
        assertEquals(2, result.rows.size)
        val ids = result.rows.map { it.id }.toSet()
        assertTrue(a.id in ids)
        assertTrue(b.id in ids)
    }

    // ---------------------------------------------------------------
    // IS NULL / IS NOT NULL — no parameter binding, pure SQL
    // ---------------------------------------------------------------

    @Test
    fun `is null filter finds unassigned tasks`() = withDb {
        val projectId = seedProject("NUL")
        val unassigned = createTask(projectId, "unassigned")
        createTask(projectId, "assigned", assigneeProfileId = callerProfileId)

        val result = taskQueryService.search(
            "assignee IS NULL",
            actingProfileId = callerProfileId,
        )
        val ids = result.rows.map { it.id }.toSet()
        assertTrue(unassigned.id in ids)
        assertTrue(result.rows.none { it.assigneeProfileId != null })
    }

    @Test
    fun `is not null filter finds assigned tasks`() = withDb {
        val projectId = seedProject("NNL")
        createTask(projectId, "unassigned")
        val assigned = createTask(projectId, "assigned", assigneeProfileId = callerProfileId)

        val result = taskQueryService.search(
            "assignee IS NOT NULL AND project = NNL",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(assigned.id, result.rows.single().id)
    }

    // ---------------------------------------------------------------
    // IN list — TEXT_ARRAY and UUID_ARRAY binding
    // ---------------------------------------------------------------

    @Test
    fun `in list with text values matches multiple summaries`() = withDb {
        val projectId = seedProject("INL")
        val a = createTask(projectId, "aaa")
        val b = createTask(projectId, "bbb")
        createTask(projectId, "ccc")

        val result = taskQueryService.search(
            """summary IN ("aaa", "bbb")""",
            actingProfileId = callerProfileId,
        )
        assertEquals(2, result.rows.size)
        val ids = result.rows.map { it.id }.toSet()
        assertTrue(a.id in ids)
        assertTrue(b.id in ids)
    }

    @Test
    fun `not in list excludes matching values`() = withDb {
        val projectId = seedProject("NIN")
        createTask(projectId, "aaa")
        val b = createTask(projectId, "bbb")

        val result = taskQueryService.search(
            """summary NOT IN ("aaa") AND project = NIN""",
            actingProfileId = callerProfileId,
        )
        assertEquals(1, result.rows.size)
        assertEquals(b.id, result.rows.single().id)
    }

    @Test
    fun `in list with name references resolves to UUID array`() = withDb {
        val projectId = seedProject("INR")
        val t = createTask(projectId, "task-in-ref")

        // Use the project key in an IN list — resolves to UUID_ARRAY binding.
        val result = taskQueryService.search(
            """project IN (INR)""",
            actingProfileId = callerProfileId,
        )
        val ids = result.rows.map { it.id }.toSet()
        assertTrue(t.id in ids)
    }

    // ---------------------------------------------------------------
    // Blank BQL — falls through to the "all tasks" path
    // ---------------------------------------------------------------

    @Test
    fun `blank bql returns all tasks ordered by modified_at desc`() = withDb {
        val projectId = seedProject("BLK")
        createTask(projectId, "first")
        createTask(projectId, "second")
        createTask(projectId, "third")

        val result = taskQueryService.search("", actingProfileId = null)
        assertTrue(result.rows.size >= 3, "expected at least 3 tasks from blank BQL")
        assertTrue(result.freeTextTerms.isEmpty())
    }

    @Test
    fun `row mapping preserves structured external references`() = withDb {
        val projectId = seedProject("EXT")
        val task = createTask(projectId, "external reference")
        transaction {
            connection().useStatement(
                "update workops.task set external_references = cast(? as jsonb) where id = ?",
            ) { statement ->
                statement.setString(1, "{\"ticket\":\"SUP-42\"}")
                statement.setObject(2, java.util.UUID.fromString(task.id.toString()))
                statement.executeUpdate()
            }
        }

        val mapped = taskQueryService.search("project = EXT", callerProfileId).rows.single()

        assertEquals("SUP-42", mapped.externalReferences?.jsonObject?.get("ticket")?.jsonPrimitive?.content)
    }

    // ---------------------------------------------------------------
    // Error handling — malformed BQL raises BqlParseException
    // ---------------------------------------------------------------

    @Test
    fun `malformed bql raises BqlParseException`() = withDb {
        seedProject("ERR")
        createTask(seedProject("ER2"), "x")
        kotlin.test.assertFailsWith<BqlParseException> {
            taskQueryService.search("=== garbage", actingProfileId = null)
        }
    }

    @Test
    fun `unknown field raises BqlParseException from validator`() = withDb {
        seedProject("UNK")
        kotlin.test.assertFailsWith<BqlParseException> {
            taskQueryService.search("nonexistent_field = foo", actingProfileId = null)
        }
    }
}
