package bosca.ksp

import com.squareup.kotlinpoet.ClassName

object Types {
    val UUID = ClassName("bosca.serialization", "UUID")
    val ProviderRegistry = ClassName("bosca.di", "ProviderRegistry")
    val ProviderRegistrar = ClassName("bosca.di", "ProviderRegistrar")
    val JsonElement = ClassName("kotlinx.serialization.json", "JsonElement")
    val ObjectProvider = ClassName("bosca.di", "ObjectProvider")
    val PubSubService = ClassName("bosca.pubsub", "PubSubService")
    val Batch = ClassName("bosca.graphql", "Batch")
    val BatchKey = ClassName("bosca.graphql", "BatchKey")
    val PropertyDataFetcher = ClassName("bosca.graphql", "PropertyDataFetcher")
    val SuspendDataFetcher = ClassName("bosca.graphql", "SuspendDataFetcher")
    val FlowDataFetcher = ClassName("bosca.graphql", "FlowDataFetcher")
    val ListSerializer = ClassName("kotlinx.serialization.builtins", "ListSerializer")
    val Tracer = ClassName("io.opentelemetry.api.trace", "Tracer")
    val Dispatcher = ClassName("bosca.graphql.dispatcher", "Dispatcher")
    val CompositeDispatcher = ClassName("bosca.graphql.dispatcher", "CompositeDispatcher")
    val Json = ClassName("kotlinx.serialization.json", "Json")
    val AuthenticationContext = ClassName("bosca.security.service", "AuthenticationContext")
    val BatchLoaderEnvironment = ClassName("bosca.graphql", "BatchLoaderEnvironment")
    val DispatchersRegistry = ClassName("bosca.graphql.dispatcher", "DispatchersRegistry")
    val DispatchersRegistrar = ClassName("bosca.graphql.dispatcher", "DispatchersRegistrar")
    val RuntimeWiring = ClassName("bosca.graphql.server", "RuntimeWiring")
    val RuntimeWiringBuilder = ClassName("bosca.graphql.server", "RuntimeWiringBuilder")
    val ResolverContext = ClassName("bosca.graphql.server", "ResolverContext")
    val TypeRuntimeWiring = ClassName("bosca.graphql.server", "TypeRuntimeWiring")
    val SchemaRegistrar = ClassName("bosca.graphql", "SchemaRegistrar")
    val GraphQLController = ClassName("bosca.graphql", "GraphQLController")
    val DefaultMappers = ClassName("bosca.db.mapper", "DefaultMappers")
    val SerializableMapper = ClassName("bosca.db.mapper", "SerializableMapper")
    val ServerCall = ClassName("bosca.server", "ServerCall")
    val PipelineContext = ClassName("bosca.pipelines", "PipelineContext")
    val Job = ClassName("bosca.sharedqueue.jobs", "Job")
    val JobConfigurationEnqueuer = ClassName("bosca.sharedqueue.jobs", "JobConfigurationEnqueuer")
    val JobQueue = ClassName("bosca.sharedqueue.jobs", "JobQueue")
    val SchedulableJobRegistrar = ClassName("bosca.scheduler", "SchedulableJobRegistrar")
    val SchedulableJob = ClassName("bosca.scheduler", "SchedulableJob")
    val PipelineEventDispatcher = ClassName("bosca.pipelines", "PipelineEventDispatcher")
    val EventCatalogRegistrar = ClassName("bosca.events.catalog", "EventCatalogRegistrar")
    val EventDescriptor = ClassName("bosca.events.catalog", "EventDescriptor")
    val EventCatalogFields = ClassName("bosca.events.catalog", "EventCatalogFields")
    val SerializerRegistrar = ClassName("bosca.serialization", "SerializerRegistrar")
    val SerializerCache = ClassName("bosca.serialization", "SerializerCache")
    val PipelineNode = ClassName("bosca.pipelines.node", "PipelineNode")
    val PipelineNodeSerializers = ClassName("bosca.pipelines.node", "PipelineNodeSerializers")
    val PipelineValue = ClassName("bosca.pipelines.node", "PipelineValue")
    val NodeInputs = ClassName("bosca.pipelines.node", "NodeInputs")
    val UUIDSerializer = ClassName("bosca.serialization", "UUIDSerializer")
    val JsonObject = ClassName("kotlinx.serialization.json", "JsonObject")
    val JsonArray = ClassName("kotlinx.serialization.json", "JsonArray")
    val NodeDescriptor = ClassName("bosca.pipelines.node", "NodeDescriptor")
    val NodeInputSlot = ClassName("bosca.pipelines.node", "NodeInputSlot")
    val NodeOutputSlot = ClassName("bosca.pipelines.node", "NodeOutputSlot")
    val NodeFieldDescriptor = ClassName("bosca.pipelines.node", "NodeFieldDescriptor")
    val NodeSettingSlot = ClassName("bosca.pipelines.node", "NodeSettingSlot")
    val NodeSettingOption = ClassName("bosca.pipelines.node", "NodeSettingOption")
    val NodeCategory = ClassName("bosca.pipelines.annotation", "NodeCategory")
    val SlotKind = ClassName("bosca.pipelines.annotation", "SlotKind")
    val SettingControl = ClassName("bosca.pipelines.annotation", "SettingControl")
    val ReferenceSource = ClassName("bosca.pipelines.annotation", "ReferenceSource")
    val SerializersModule = ClassName("kotlinx.serialization.modules", "SerializersModule")
}
