package bosca.localization.model

import bosca.db.annotation.DbMapper
import bosca.db.mapper.EnumMapper
import kotlinx.serialization.Serializable

/**
 * Identifies the source that produced a translation, enabling review workflows
 * and reporting that distinguish human-authored work from machine or external output.
 *
 * - [HUMAN]: entered directly by a human translator via the admin UI or API
 * - [AI]: generated by an automated AI pipeline; typically requires review before publishing
 * - [IMPORT]: loaded from a source file (e.g. CLI upload of an existing strings file)
 * - [SYNC]: pulled from an external translation management platform such as Crowdin
 */
@DbMapper(TranslationOriginMapper::class)
@Serializable
enum class TranslationOrigin {
    HUMAN,
    AI,
    IMPORT,
    SYNC
}

object TranslationOriginMapper : EnumMapper<TranslationOrigin>({ TranslationOrigin.valueOf(it.uppercase()) })
