{{- /*
Renders Kubernetes Secrets for each entry in .Values.secrets where create: true.
*/}}
{{- $labels := include "bosca-common.labels" . -}}

{{- with .Values.secrets.artifacts }}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  {{ .key }}: {{ .value | quote }}
{{- end }}
{{- end }}

{{- with .Values.secrets.tracking }}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  {{ .key }}: {{ .value | quote }}
{{- end }}
{{- end }}

{{- with .Values.secrets.nats }}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  {{ .key }}: {{ .value | quote }}
{{- end }}
{{- end }}

{{- with .Values.secrets.analytics }}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  {{ .key }}: {{ .value | quote }}
{{- end }}
{{- end }}

{{- with .Values.secrets.localization }}
{{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- $labels | nindent 4 }}
type: Opaque
stringData:
  {{ .key }}: {{ .value | quote }}
{{- end }}
{{- end }}
