<script setup lang="ts">
import gql from 'graphql-tag'
import JsonEditorVue from 'json-editor-vue'

const props = defineProps<{ releaseId: string; canManage: boolean }>()
const { accent } = useCurrentSubsystem()
const { useAsyncQuery, mutation } = useGraphQL()
const toast = useToast()

interface LocalizedNotes {
  locale: string
  playReleaseNotes: string
  appStoreWhatsNew: string
  testFlightWhatToTest: string
}
interface VersionNotes {
  id: string
  versionId: string
  sourceLocale: string
  generatedAt: string | null
  manuallyEdited: boolean
  variants: LocalizedNotes[]
  workOpsVersion: { name: string; project: { name: string } }
}

const notesGql = gql`
  query VersionReleaseNotesCard($releaseId: UUID!) {
    workOps { multiRepo { versionReleaseNotes(releaseId: $releaseId) {
      id versionId sourceLocale generatedAt manuallyEdited variants
      workOpsVersion { name project { name } }
    } } }
  }
`
const { data, status, refresh } = useAsyncQuery<{ workOps: { multiRepo: { versionReleaseNotes: VersionNotes[] } } }>(
  'version-release-notes-card', notesGql, { releaseId: computed(() => props.releaseId) }, { server: false },
)
const notes = computed(() => data.value?.workOps?.multiRepo?.versionReleaseNotes ?? [])

const generating = ref(false)
async function generate() {
  generating.value = true
  try {
    await mutation(gql`
      mutation GenerateVersionReleaseNotes($releaseId: UUID!) {
        workOps { multiRepo { autoGenerateVersionReleaseNotes(releaseId: $releaseId) { id versionId } } }
      }
    `, { releaseId: props.releaseId })
    toast.success('Localized release notes generated from tagged changes')
    await refresh()
  }
  catch (error: unknown) { toast.error(error instanceof Error ? error.message : 'Failed to generate release notes') }
  finally { generating.value = false }
}

const editing = ref<VersionNotes | null>(null)
const draft = ref<LocalizedNotes[]>([])
const saving = ref(false)
function openEdit(note: VersionNotes) {
  editing.value = note
  draft.value = structuredClone(note.variants)
}
async function save() {
  if (!editing.value) return
  saving.value = true
  try {
    await mutation(gql`
      mutation EditVersionReleaseNotes(
        $releaseId: UUID!, $versionId: UUID!, $variants: JSON!
      ) {
        workOps { multiRepo { editVersionReleaseNotes(
          releaseId: $releaseId, versionId: $versionId, variants: $variants
        ) { id versionId } } }
      }
    `, {
      releaseId: props.releaseId,
      versionId: editing.value.versionId,
      variants: draft.value,
    })
    toast.success('Version release notes saved')
    editing.value = null
    await refresh()
  }
  catch (error: unknown) { toast.error(error instanceof Error ? error.message : 'Failed to save release notes') }
  finally { saving.value = false }
}
defineExpose({ refresh })
</script>

<template>
  <SectionCard title="Release notes" subtitle="Localized store copy read directly from localization" padded>
    <div class="notes-actions">
      <Button
        size="sm"
        icon="refresh"
        :disabled="generating || !canManage"
        title="Generate drafts from each version's tagged Git range"
        @click="generate">Generate from tags</Button>
    </div>
    <p v-if="status === 'pending' && !notes.length" class="notes-empty">Loading…</p>
    <p v-else-if="!notes.length" class="notes-empty">
      No version notes yet. Generate them after the release's repository tags exist.
    </p>
    <div v-else class="version-list">
      <section v-for="note in notes" :key="note.id" class="version-note">
        <header>
          <div>
            <h5>{{ note.workOpsVersion.project.name }} · {{ note.workOpsVersion.name }}</h5>
            <span>
              {{ note.manuallyEdited ? 'Manually edited' : 'Generated by Kit' }}
              <template v-if="note.generatedAt"> · {{ new Date(note.generatedAt).toLocaleString() }}</template>
            </span>
          </div>
          <Button
            size="xs"
            icon="edit"
            :disabled="!canManage"
            @click="openEdit(note)">Edit</Button>
        </header>
        <div class="locale-list">
          <article v-for="variant in note.variants" :key="variant.locale" class="locale-note">
            <h6>{{ variant.locale }}<span v-if="variant.locale === note.sourceLocale">source</span></h6>
            <dl>
              <dt>Google Play</dt><dd>{{ variant.playReleaseNotes }}</dd>
              <dt>App Store</dt><dd>{{ variant.appStoreWhatsNew }}</dd>
              <dt>TestFlight</dt><dd>{{ variant.testFlightWhatToTest }}</dd>
            </dl>
          </article>
        </div>
      </section>
    </div>

    <Modal
      v-if="editing"
      :title="`Edit ${editing.workOpsVersion.name} release notes`"
      icon="edit"
      :accent="accent"
      width="760px"
      @close="editing = null">
      <p class="editor-help">
        Keep one entry per configured BCP-47 locale. All three store fields are required at submission time.
      </p>
      <p class="source-field">Source locale: {{ editing.sourceLocale }}</p>
      <JsonEditorVue
        :model-value="draft"
        :main-menu-bar="false"
        :navigation-bar="false"
        class="jse-theme-dark notes-editor"
        @update:model-value="draft = $event" />
      <template #footer>
        <Button :disabled="saving" @click="editing = null">Cancel</Button>
        <Button
          primary
          :accent="accent"
          :disabled="saving"
          @click="save">Save notes</Button>
      </template>
    </Modal>
  </SectionCard>
</template>

<style scoped>
.notes-actions { display: flex; justify-content: flex-end; margin-bottom: 10px; }
.notes-empty, .editor-help { margin: 0; font-size: 11.5px; color: var(--fg-3); line-height: 1.5; }
.version-list, .locale-list { display: flex; flex-direction: column; gap: 10px; }
.version-note { padding: 10px; border: 1px solid var(--line); border-radius: 6px; }
.version-note > header { display: flex; align-items: flex-start; justify-content: space-between; gap: 10px; margin-bottom: 10px; }
.version-note h5 { margin: 0 0 2px; font-size: 11px; color: var(--fg-1); }
.version-note header span { font-size: 9.5px; color: var(--fg-3); }
.locale-note { padding: 9px; background: var(--bg-2); border-radius: 5px; }
.locale-note h6 { display: flex; align-items: center; gap: 6px; margin: 0 0 7px; font-size: 10px; color: var(--fg-1); }
.locale-note h6 span { padding: 1px 5px; border-radius: 8px; background: color-mix(in srgb, var(--accent) 14%, transparent); color: var(--accent); font-size: 8px; text-transform: uppercase; }
.locale-note dl { display: grid; grid-template-columns: 78px 1fr; gap: 6px 9px; margin: 0; font-size: 10px; line-height: 1.4; }
.locale-note dt { color: var(--fg-3); }
.locale-note dd { margin: 0; color: var(--fg-1); white-space: pre-wrap; }
.editor-help { margin-bottom: 10px; }
.source-field { margin: 0 0 10px; font-size: 10px; color: var(--fg-2); }
.notes-editor { min-height: 390px; }
</style>
