packages:
  - "git-search-index"

bosca:
  server:
    port: "${GIT_HTTP_PORT:8091}"
    development: "${GIT_DEVELOPMENT:false}"

database:
  postgres:
    url: "${DATABASE_URL:jdbc:postgresql://localhost:5433/bosca}"
    user: "${DATABASE_USER:bosca}"
    password: "${DATABASE_PASSWORD:bosca}"
    maxConnections: "${DATABASE_MAX_CONNECTIONS:20}"

cache:
  type: nats

jobQueue:
  factory: nats

pubsub:
  type: nats

distributedLock:
  type: nats

nats:
  url: "$NATS_HOST:localhost:4222"
  token: "$NATS_TOKEN:OAVKZTG7ST62YCPUJYJ6LBQDMKLAUD4NRBPZ4GXUXNUJW2ATCFKKYGHV"
  username: "$NATS_USERNAME:"
  password: "$NATS_PASSWORD:"

counter:
  type: nats

jwt:
  domain: "$JWT_DOMAIN:localhost"
  admin-domain: "$JWT_ADMIN_DOMAIN:localhost"
  audience: "$JWT_AUDIENCE:Bosca"
  realm: "$JWT_REALM:Bosca"
  issuer: "$JWT_ISSUER:Bosca"
  secret: "$JWT_SECRET:c534b2595b38f5d9cb33f8cd05996c95"
  cookie-secure: ${JWT_COOKIE_SECURE:false}
  expiration-time: ${JWT_EXPIRATION_TIME:2592000}

analyticsServer:
  appId: "$ANALYTICS_APP_ID:bosca-git-server"
  url: "$ANALYTICS_SERVER_URL:http://localhost:8081"

app:
  url: "${APP_URL:http://localhost:3000}"

git:
  url: "${GIT_URL:http://localhost:8091}"

pipeline:
  secretKey: "$PIPELINE_SECRET_KEY:dGhpcy1pcy1hLWRldi1vbmx5LXNlY3JldC1rZXktMzI="

meilisearch:
  url: "$MEILISEARCH_URL:http://localhost:7701"
  apiKey: "$MEILISEARCH_API_KEY:p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M"
  indexPrefix: "$MEILISEARCH_INDEX_PREFIX:"

content:
  storage:
    type: "$STORAGE_TYPE:s3"
    bucket: "$STORAGE_BUCKET:storage"
    urlUploadPrefix: "$STORAGE_URL_UPLOAD_PREFIX:http://localhost:8080"
    forcePathStyle: ${STORAGE_FORCE_PATH_STYLE:true}
    region: "$STORAGE_REGION:us-east-1"
    urlPrefix: "$STORAGE_URL_PREFIX:http://localhost:8080"
    endpoint: "$STORAGE_ENDPOINT:http://localhost:8000"
    accessKeyId: "$STORAGE_ACCESS_KEY_ID:bosca-s3"
    accessKeySecret: "$STORAGE_ACCESS_KEY_SECRET:bosca-s3"
  urlSigner:
    secretKey: "$STORAGE_URL_SIGNER_SECRET_KEY:10df7d451e8365cd6a8d43d408a25c82"
