package bosca.events.catalog

import kotlinx.serialization.KSerializer

/**
 * Per-module supplier of [EventDescriptor]s for every `@JobEvent` declared in that module.
 *
 * One implementation is generated by KSP for each module that declares events (see
 * `EventCatalogRegistryGenerator`). Each is registered into the DI container as a named
 * [ObjectProvider][bosca.di.ObjectProvider] so [EventCatalogService] can aggregate them
 * across all loaded modules via [ProviderRegistry.findAll][bosca.di.ProviderRegistry].
 */
interface EventCatalogRegistrar {

    /** The event descriptors contributed by this module. */
    val events: List<EventDescriptor>

    /**
     * The **explicitly compiled** event serializer per fqdn (`X.serializer()`, emitted by KSP).
     * Lets consumers that only hold an event's fqdn + JSON payload (e.g. a queued trigger job
     * feeding a pipeline) deserialize back to the typed event without any reflective lookup —
     * GraalVM-native safe.
     */
    val serializers: Map<String, KSerializer<*>> get() = emptyMap()
}
