{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bosca-gateway.fullname" . }}
  labels:
    {{- include "bosca-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  bosca-api-token: {{ .Values.secrets.boscaApiToken | b64enc | quote }}
{{- end }}
