Args = --enable-url-protocols=http,https \
       --initialize-at-build-time=ch.qos.logback,org.slf4j,org.xml.sax,net.fortuna.ical4j \
       -H:+ReportExceptionStackTraces \
       -H:+SharedArenaSupport
