connector.name=iceberg

iceberg.catalog.type=jdbc

iceberg.jdbc-catalog.catalog-name=bosca
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres-warehouse:5432/bosca-warehouse
iceberg.jdbc-catalog.connection-user=bosca-warehouse
iceberg.jdbc-catalog.connection-password=bosca-warehouse

iceberg.jdbc-catalog.default-warehouse-dir=s3://warehouse/warehouse

fs.native-s3.enabled=true

s3.region=us-east-1

s3.endpoint=http://s3proxy:8000
s3.path-style-access=true
s3.aws-access-key=bosca-s3
s3.aws-secret-key=bosca-s3
